const N=20,$=x=>document.getElementById(x);
const Q=Array.from({length:N},()=>({d:null,a:null,w:""}));
const QM=new Map(),AM=new Map();let i=0,p=0,done=false;
const norm=s=>s.trim().toLocaleLowerCase("sk-SK").normalize("NFC");
const key=s=>norm(s.replace(/\.[^.]+$/,"")).normalize("NFD").replace(/[\u0300-\u036f]/g,"");
const valid=q=>q.d&&q.a&&q.w.trim();
function fileBox(kind,n,text){return '<label class="drop" data-kind="'+kind+'" data-n="'+n+'"><span>'+text+'</span><input type="file" accept="image/*"></label>'}
function cards(){const g=$("grid");g.replaceChildren(...Q.map((q,n)=>{const c=document.createElement("article");c.className="card";c.id="q"+n;c.innerHTML='<div class="head"><strong>Hádanka '+(n+1)+'</strong><span class="status"></span></div><label class="label">Detail na hádanie</label>'+fileBox("d",n,"Nahrať detail 🔎")+'<label class="label">Slovná odpoveď — nominatív</label><input class="word" data-n="'+n+'" value="'+q.w+'" placeholder="napr. melón"><label class="label">Obrázok správnej odpovede</label>'+fileBox("a",n,"Nahrať odpoveďový obrázok 🖼️");return c}));g.querySelectorAll(".drop input").forEach(x=>x.onchange=e=>load(e,x.closest(".drop")));g.querySelectorAll(".word").forEach(x=>x.oninput=e=>{Q[+x.dataset.n].w=e.target.value;refresh()});refresh()}
function load(e,box){const f=e.target.files[0];if(!f)return;Q[+box.dataset.n][box.dataset.kind]=URL.createObjectURL(f);box.innerHTML='<img src="'+Q[+box.dataset.n][box.dataset.kind]+'"><input type="file" accept="image/*">';box.querySelector("input").onchange=x=>load(x,box);refresh()}
function refresh(){const r=Q.filter(valid).length;$("ready").textContent="Pripravené: "+r+" / 20";$("start").disabled=r<N;Q.forEach((q,n)=>{const c=$("q"+n);c.classList.toggle("done",valid(q));c.querySelector(".status").textContent=valid(q)?"✓ pripravená":"čaká na údaje"})}
function readFolder(e,map){[...e.target.files].filter(f=>f.type.startsWith("image/")).forEach(f=>map.set(key(f.name),URL.createObjectURL(f)))}
function match(){Q.forEach(q=>{const k=key(q.w);if(QM.has(k))q.d=QM.get(k);if(AM.has(k))q.a=AM.get(k)});cards()}
function view(v){$("editor").classList.toggle("hidden",v!=="e");$("play").classList.toggle("hidden",v!=="p");$("result").classList.toggle("hidden",v!=="r");$("te").classList.toggle("active",v==="e");$("th").classList.toggle("active",v==="p")}
function begin(){if(Q.some(q=>!valid(q)))return;i=p=0;view("p");draw()}
function draw(){done=false;const q=Q[i];$("counter").textContent="Hádanka "+(i+1)+" z 20";$("score").textContent="⭐ "+p+" bodov";$("bar").style.width=(i+1)*5+"%";$("detail").src=q.d;$("typed").value="";$("form").classList.remove("hidden");$("feedback").textContent="";$("reveal").classList.add("hidden");$("next").classList.add("hidden")}
function send(e){e.preventDefault();if(done||!$("typed").value.trim())return;done=true;const q=Q[i],yes=norm($("typed").value)===norm(q.w);if(yes){p++;$("feedback").textContent="Správne! 🎉";$("feedback").className="feedback good"}else{$("feedback").textContent="Správna odpoveď je: "+q.w+".";$("feedback").className="feedback bad"}$("score").textContent="⭐ "+p+" bodov";$("form").classList.add("hidden");$("revealword").textContent="Správna odpoveď: "+q.w;$("answerimg").src=q.a;$("reveal").classList.remove("hidden");$("next").classList.remove("hidden")}
function next(){if(++i<N)draw();else{view("r");const x=Math.round(p/N*100);$("final").textContent=p+" / 20 bodov ("+x+" %)";$("finaltext").textContent=x===100?"Dokonalý letný výkon! 🏆":"Skús to znova a zlepši si úspešnosť."}}
$("qfolder").onchange=e=>readFolder(e,QM);$("afolder").onchange=e=>readFolder(e,AM);$("match").onclick=match;$("te").onclick=()=>view("e");$("th").onclick=()=>view("p");$("start").onclick=begin;$("form").onsubmit=send;$("next").onclick=next;$("again").onclick=begin;cards();
