const $=id=>document.getElementById(id);
const words=["ananás","banán","batoh","bazén","fotoaparát","hrad","jahody","koleso","kufor","lehátko","lietadlo","limonáda","lopta","melón","mušle","okuliare","plavky","zmrzlina","šiltovka","žabky"];
const imageUrl=(folder,word)=>"uploads/"+folder+"/"+encodeURIComponent(word)+".jpg";
const questions=words.map(word=>({word,detail:imageUrl("otazky",word),answer:imageUrl("odpovede",word)}));
let order=[],index=0,points=0,answered=false;
const norm=s=>s.trim().toLocaleLowerCase("sk-SK").normalize("NFC");
const shuffled=a=>[...a].sort(()=>Math.random()-.5);
function start(){order=shuffled(questions);index=points=0;$("intro").classList.add("hidden");$("result").classList.add("hidden");$("game").classList.remove("hidden");draw()}
function draw(){answered=false;const q=order[index];$("counter").textContent="Hádanka "+(index+1)+" z "+questions.length;$("score").textContent="⭐ "+points+" bodov";$("bar").style.width=((index+1)/questions.length*100)+"%";$("detail").src=q.detail;$("typed").value="";$("typed").disabled=false;$("form").classList.remove("hidden");$("feedback").textContent="";$("feedback").className="feedback";$("reveal").classList.add("hidden");$("next").classList.add("hidden");setTimeout(()=>$("typed").focus(),0)}
function submit(e){e.preventDefault();if(answered)return;const typed=$("typed").value;if(!typed.trim()){$("feedback").textContent="Najprv napíš odpoveď.";$("feedback").className="feedback bad";return}answered=true;const q=order[index],correct=norm(typed)===norm(q.word);if(correct){points++;$("feedback").textContent="Správne! 🎉";$("feedback").className="feedback good"}else{$("feedback").textContent="Správna odpoveď je: "+q.word+".";$("feedback").className="feedback bad"}$("score").textContent="⭐ "+points+" bodov";$("typed").disabled=true;$("form").classList.add("hidden");$("reveal-word").textContent="Správna odpoveď: "+q.word;$("answer-image").src=q.answer;$("answer-image").alt=q.word;$("reveal").classList.remove("hidden");$("next").classList.remove("hidden")}
function next(){if(++index<questions.length)draw();else{const percent=Math.round(points/questions.length*100);$("game").classList.add("hidden");$("result").classList.remove("hidden");$("final").textContent=points+" / "+questions.length+" bodov ("+percent+" %)";$("final-text").textContent=percent===100?"Dokonalý letný výkon! 🏆":percent>=75?"Parádne — máš skvelé oko na letné detaily! 🌞":"Krásny výlet hádankami. Skús to ešte raz a zlepši percentá! 🏖️"}}
$("start").onclick=start;$("again").onclick=start;$("form").onsubmit=submit;$("next").onclick=next;
