(function () {
  var verbPatterns = [
    { present: "beží", past: "bežal", future: "bude bežať" },
    { present: "skáče", past: "skákal", future: "bude skákať" },
    { present: "číta", past: "čítal", future: "bude čítať" },
    { present: "píše", past: "písal", future: "bude písať" },
    { present: "kreslí", past: "kreslil", future: "bude kresliť" },
    { present: "spieva", past: "spieval", future: "bude spievať" },
    { present: "tancuje", past: "tancoval", future: "bude tancovať" },
    { present: "pláva", past: "plával", future: "bude plávať" },
    { present: "varí", past: "varil", future: "bude variť" },
    { present: "pečie", past: "piekol", future: "bude piecť" },
    { present: "umýva", past: "umýval", future: "bude umývať" },
    { present: "upratuje", past: "upratoval", future: "bude upratovať" },
    { present: "hrá", past: "hral", future: "bude hrať" },
    { present: "telefonuje", past: "telefonoval", future: "bude telefonovať" },
    { present: "rozpráva", past: "rozprával", future: "bude rozprávať" },
    { present: "počúva", past: "počúval", future: "bude počúvať" },
    { present: "pozerá", past: "pozeral", future: "bude pozerať" },
    { present: "smeje sa", past: "smial sa", future: "bude sa smiať" },
    { present: "spí", past: "spal", future: "bude spať" },
    { present: "je", past: "jedol", future: "bude jesť" },
    { present: "pije", past: "pil", future: "bude piť" },
    { present: "nosí", past: "nosil", future: "bude nosiť" },
    { present: "obúva si", past: "obúval si", future: "bude si obúvať" },
    { present: "cestuje", past: "cestoval", future: "bude cestovať" },
    { present: "nakupuje", past: "nakupoval", future: "bude nakupovať" },
    { present: "učí sa", past: "učil sa", future: "bude sa učiť" },
    { present: "odpovedá", past: "odpovedal", future: "bude odpovedať" },
    { present: "počíta", past: "počítal", future: "bude počítať" },
    { present: "stavia", past: "staval", future: "bude stavať" },
    { present: "otvára", past: "otváral", future: "bude otvárať" },
    { present: "zatvára", past: "zatváral", future: "bude zatvárať" },
    { present: "robí", past: "robil", future: "bude robiť" },
    { present: "pomáha", past: "pomáhal", future: "bude pomáhať" },
    { present: "hľadá", past: "hľadal", future: "bude hľadať" },
    { present: "zbiera", past: "zbieral", future: "bude zbierať" },
    { present: "sadí", past: "sadil", future: "bude sadiť" },
    { present: "polieva", past: "polieval", future: "bude polievať" },
    { present: "sedí", past: "sedel", future: "bude sedieť" },
    { present: "stojí", past: "stál", future: "bude stáť" },
    { present: "kráča", past: "kráčal", future: "bude kráčať" },
    { present: "letí", past: "letel", future: "bude letieť" },
    { present: "jazdí", past: "jazdil", future: "bude jazdiť" },
    { present: "tlačí", past: "tlačil", future: "bude tlačiť" },
    { present: "ťahá", past: "ťahal", future: "bude ťahať" },
    { present: "otáča", past: "otáčal", future: "bude otáčať" },
    { present: "fotografuje", past: "fotografoval", future: "bude fotografovať" },
    { present: "maľuje", past: "maľoval", future: "bude maľovať" },
    { present: "strihá", past: "strihal", future: "bude strihať" },
    { present: "šije", past: "šil", future: "bude šiť" },
    { present: "lepí", past: "lepil", future: "bude lepiť" },
    { present: "skladá", past: "skladal", future: "bude skladať" },
    { present: "ukazuje", past: "ukazoval", future: "bude ukazovať" },
    { present: "opakuje", past: "opakoval", future: "bude opakovať" },
    { present: "skúša", past: "skúšal", future: "bude skúšať" },
    { present: "cvičí", past: "cvičil", future: "bude cvičiť" },
    { present: "prehráva", past: "prehrával", future: "bude prehrávať" },
    { present: "zapína", past: "zapínal", future: "bude zapínať" },
    { present: "vypína", past: "vypínal", future: "bude vypínať" },
    { present: "čistí", past: "čistil", future: "bude čistiť" },
    { present: "zametá", past: "zametal", future: "bude zametať" },
    { present: "kope", past: "kopal", future: "bude kopať" },
    { present: "chytá", past: "chytal", future: "bude chytať" },
    { present: "háda", past: "hádal", future: "bude hádať" },
    { present: "kričí", past: "kričal", future: "bude kričať" },
    { present: "šepká", past: "šepkal", future: "bude šepkať" },
    { present: "dýcha", past: "dýchal", future: "bude dýchať" },
    { present: "padá", past: "padal", future: "bude padať" },
    { present: "rastie", past: "rástol", future: "bude rásť" },
    { present: "kvitne", past: "kvitol", future: "bude kvitnúť" },
    { present: "svieti", past: "svietil", future: "bude svietiť" },
    { present: "prší", past: "pršalo", future: "bude pršať" },
    { present: "sneží", past: "snežilo", future: "bude snežiť" },
    { present: "veje", past: "vial", future: "bude viať" },
    { present: "žije", past: "žil", future: "bude žiť" },
    { present: "pracuje", past: "pracoval", future: "bude pracovať" },
    { present: "oddychuje", past: "oddychoval", future: "bude oddychovať" },
    { present: "balí", past: "balil", future: "bude baliť" },
    { present: "učí", past: "učil", future: "bude učiť" },
    { present: "lezie", past: "liezol", future: "bude liezť" },
    { present: "češe", past: "česal", future: "bude česať" },
    { present: "prehadzuje", past: "prehadzoval", future: "bude prehadzovať" },
    { present: "budí sa", past: "budil sa", future: "bude sa budiť" }
  ];

  var bank = [];
  var i;

  for (i = 0; i < verbPatterns.length; i += 1) {
    bank.push({ text: verbPatterns[i].present, tense: "present" });
    bank.push({ text: verbPatterns[i].past, tense: "past" });
    bank.push({ text: verbPatterns[i].future, tense: "future" });
  }

  window.VERB_BANK = bank;
}());
