/* Autorské otázky. Formát: otázka | správna odpoveď | distraktor | distraktor | vysvetlenie.
   Rozdelenie podľa ročníkov je didaktická adaptácia, nie oficiálna skúška ŠVP.
   Podklady a ročníkové okruhy: SOURCES.md.
   Redakčná revízia: situačné zadania, vierohodné omyly, porovnateľná dĺžka možností.
   Pri ďalších úpravách zachovať jedinú správnu odpoveď v uvedenej situácii. */
(function (root) {
'use strict';
const data = `
@1|civil
V škole zaznie poplach. Čo urobíš?|Idem s triedou podľa učiteľa.|Idem k východu sám, cestu už poznám.|Najprv si vezmem bundu, aby mi nebola zima.|Pri evakuácii sa drž triedy a pokynov učiteľa.
V škole horí zásuvka. Dospelý už volá pomoc. Kto má vybavenie na hasenie požiaru?|Hasiči.|Zdravotníci.|Policajti.|Hasiči sú vybavení na hasenie. Pri udalosti môžu pomáhať aj ostatné záchranné zložky.
Nájdeš zápalky. Čo je bezpečné?|Nechám ich na mieste a poviem dospelému.|Odnesiem ich sám do školskej tašky.|Odložím ich do koša medzi papier.|Zápalky nepatria do detských rúk.
Ktoré číslo je spoločnou tiesňovou linkou pre pomoc v núdzi?|112.|155.|150.|112 je spoločná tiesňová linka. Čísla 155 a 150 patria zdravotnej službe a hasičom.
Pri odchode z triedy počas poplachu…|kráčam s triedou podľa pokynov.|čakám v triede, kým bude chodba prázdna.|predbehnem triedu, aby som otvoril východ.|Pokojný presun pomáha celej triede dostať sa do bezpečia.
Na chodbe vidíš dym. Čo urobíš?|Upozorním dospelého a zostanem mimo dymu.|Prejdem cez dym so zakrytými ústami.|Otvorím dvere do dymu, nech vyvetrám.|Dym je nebezpečný. Nevstupuj do zadymeného priestoru.
Na čo slúži siréna civilnej ochrany?|Upozorňuje na možné nebezpečenstvo.|Hovorí, že všetci majú hneď ísť domov.|Oznamuje, že nebezpečenstvo už pominulo.|Po siréne počúvaj dospelých a oficiálne informácie.
Trieda prišla na miesto zhromaždenia. Čo urobíš?|Zostanem pri učiteľovi až do ďalšieho pokynu.|Odídem k rodičovi, ktorého vidím za plotom.|Prejdem k druhej triede za kamarátom.|Učiteľ musí vedieť, že sú všetci v bezpečí.
Na stole pri sviečke sú tri veci. Ktorú treba od plameňa odsunúť pre riziko vznietenia?|Papierový obrúsok.|Kovovú lyžičku.|Keramický tanier.|Papier môže ľahko začať horieť. Aj iné predmety sa pri plameni môžu zohriať, preto so sviečkou manipuluje dospelý.
Kedy môžeš volať na 112?|Keď je niekto vo vážnom nebezpečenstve.|Keď potrebujem zistiť cestu domov.|Keď si chcem overiť telefónne číslo lekára.|Zbytočný hovor môže zdržať pomoc niekomu inému.
@1|aid
Kamarát spadol a poranil sa. Čo urobíš?|Zavolám dospelého a poviem, kde kamarát je.|Odvediem kamaráta bez pýtania do triedy.|Počkám, či si poranenie všimne učiteľ sám.|Malý školák pomáha najmä rýchlym privolaním dospelého.
V lekárničke hľadáš vec na prekrytie malej ranky. Čo vyberieš?|Zabalenú náplasť.|Trojrohú šatku.|Jednorazovú rukavicu.|Na malú vyčistenú ranku slúži náplasť. Šatka pomáha napríklad podoprieť ruku a rukavica chráni pri ošetrovaní.
Nájdeš na stole tabletku. Čo urobíš?|Nechám ju tak a upozorním dospelého.|Odložím ju medzi ostatné lieky.|Dám ju dospelému priamo do pohára s vodou.|Neznámy liek môže poškodiť zdravie.
Čím sa zakryje malá vyčistená odrenina?|Čistou náplasťou.|Papierovou vreckovkou.|Suchým rukávom trička.|Čisté krytie pomáha chrániť ranku pred nečistotami.
Čo povieš dospelému, keď kamarát potrebuje pomoc?|Kde kamarát je a čo sa mu stalo.|Ktorý kamarát spadol a kto sa s ním hráva.|Ako dávno začala prestávka a kto je vonku.|Miesto a opis udalosti pomôžu dospelému rýchlo zasiahnuť.
Pred jedlom máš ruky bez viditeľnej špiny. Čo urobíš?|Umyjem si ich vodou a mydlom.|Utriem si ich do čistého uteráka.|Rýchlo si opláchnem iba končeky prstov.|Nečistoty a mikróby nemusia byť viditeľné; umývame celé ruky vodou a mydlom.
Kamarát plače po páde. Ako mu pomôžeš?|Pokojne ho oslovím a privolám dospelého.|Sľúbim mu, že o páde nikomu nepoviem.|Presvedčím ho, nech najprv skúsi dobehnúť do triedy.|Pokojné slová a dospelý pomocník sú dobrý začiatok pomoci.
Na čo slúži obväz?|Na upevnenie krytia poranenia.|Na umytie ranky pred ošetrením.|Na nahradenie rukavíc pri dotyku s krvou.|Obväz je zdravotnícka pomôcka, preto ho udržiavame čistý.
Kamarát má poranenie, ktoré potrebuje ošetriť. Ktorý pomocník sa venuje najmä zdraviu?|Zdravotník.|Hasič.|Policajt.|Zdravotníci poskytujú zdravotnú starostlivosť. Základnú pomoc môžu poskytnúť aj ďalší vyškolení ľudia.
Keď ma počas vyučovania silno bolí brucho…|poviem o bolesti učiteľovi hneď.|počkáme s kamarátom až na ďalšiu prestávku.|najprv vyskúšam, či bolesť prejde pri behu.|O zdravotných ťažkostiach povedz dospelému, ktorý sa o teba stará.
@1|orientation
Čo ti pomôže zapamätať si cestu do školy?|Budova školy a stála križovatka.|Zaparkovaná dodávka a rad bicyklov.|Stánok na kolieskach a skupina ľudí.|Stále orientačné body sú spoľahlivejšie než pohybujúce sa veci.
[map] Stojíš na mape pri škole. Ktorým smerom po obrázku sa vydáš k lesu?|Doprava.|Doľava.|Nahor.|Les je na obrázku napravo od školy. Smer určujeme podľa tejto mapy, nie podľa natočenia tela.
Na výlete nevidíš svoju skupinu. Čo urobíš?|Zostanem na bezpečnom mieste a zavolám na pomoc.|Vrátim sa sám skratkou k poslednej zastávke.|Pôjdem za turistami, ktorí idú predo mnou.|Náhodné blúdenie môže vzdialiť dieťa od skupiny.
Čo zobrazuje mapa?|Miesta a ich vzájomnú polohu.|Poradie zastávok bez údajov o ich polohe.|Čas príchodu na každé zobrazené miesto.|Mapa pomáha zistiť, kde sa miesta nachádzajú.
Kde si s dospelým vyzdvihneš liek na lekársky predpis?|V lekárni.|V drogérii.|V optike.|Lieky na predpis vydáva lekáreň. Drogéria ani optika túto úlohu nenahrádzajú.
Na výlet treba vodu aj ochranu pred dažďom. Ktorý batoh je pripravený?|S vodou a ľahkým pršiplášťom.|S desiatou a náhradnými ponožkami.|S čiapkou a slnečnými okuliarmi.|Každá výbava má svoj účel. Zadanie vyžaduje pitie aj ochranu pred dažďom.
Ako sa pohybuješ na školskom výlete?|Zostávam so skupinou v dohľade učiteľa.|Počkám na skupinu na ďalšom rázcestí.|Kráčam s kamarátom za zákrutou pred skupinou.|Skupina sa vie lepšie postarať o bezpečnosť svojich členov.
Čo je orientačný bod?|Veža kostola pri námestí.|Autobus stojaci pri námestí.|Predavač pri vchode na námestie.|Výrazná stála stavba pomáha rozoznať miesto.
Na pomôcke z obrázka sa voľne otáča strelka. Na čo ju použiješ?|Na určenie smeru severu.|Na zistenie zostávajúcej vzdialenosti.|Na odmeranie dĺžky výletu.|Strelka kompasu pomáha určiť sever. Vzdialenosť ani čas kompas sám nemeria.
Kam sa obrátiš, keď v škole nevieš nájsť triedu?|Na učiteľa alebo pracovníka školy.|Na prvú otvorenú triedu bez označenia.|Na spolužiaka, ktorý tiež hľadá a iba háda.|V neznámom priestore školy pomôže dôveryhodný dospelý.
@1|nature
Kam patrí obal z desiaty počas výletu?|Odložím ho do batohu a odnesiem ku košu.|Nechám ho vedľa plného koša na chodníku.|Schovám ho pod kameň, aby ho vietor neodniesol.|Odpad z výletu odnášame so sebou.
Na lúke uvidíš pekný kvet. Čo je šetrné?|Pozriem si ho a nechám ho na mieste.|Odtrhnem jeden kvet, ostatné nechám.|Vykopem ho a zasadím doma do črepníka.|Rastliny sú potravou a domovom pre ďalšie organizmy.
Nájdeš vtáčie hniezdo. Čo urobíš?|Pozriem sa z diaľky a vzdialim sa.|Pristúpim bližšie, aby som spočítal vajíčka.|Chvíľu postojím tesne pri hniezde a počkám na vtáka.|Hniezda nerušíme a nedotýkame sa vajec.
Ako sa správaš k cudziemu psovi?|Počkám na dovolenie majiteľa a nepribližujem sa sám.|Pohladím ho, ak pokojne stojí a nešteká.|Ponúknem mu kúsok desiaty, nech si na mňa zvykne.|Aj pokojné zviera sa môže zľaknúť a brániť.
Pri čistení zubov šetríš vodou tak, že…|vodu zavriem, keď si práve čistím zuby.|pustím slabší prúd a nechám ho tiecť po celý čas.|nechám vodu tiecť len počas všetkých pohybov kefkou.|Vodu používame len vtedy, keď ju potrebujeme.
Nový stromček potrebuje po výsadbe vodu. Ako mu s dospelým pomôžeš?|Polejem pôdu pri koreňoch.|Postriekam iba listy a kmeň.|Nalejem vodu na chodník vedľa stromčeka.|Vodu strom prijíma najmä koreňmi. Zálievku smerujeme ku koreňom podľa potrieb stromčeka.
Ako sa správaš v lese?|Hovorím potichu a zvieratá sledujem z diaľky.|Zavolám na zviera, aby sa ku mne otočilo.|Napodobňujem zvuky mláďaťa, nech zviera príde bližšie.|Tichšie správanie menej ruší lesné živočíchy.
Nájdeš neznáme bobule. Čo urobíš?|Neochutnám ich ani po opláchnutí.|Ochutnám ich, ak ich jedia vtáky.|Zjem ich, ak sa podobajú plodom zo záhrady.|Niektoré plody sú jedovaté, aj keď vyzerajú lákavo.
Čo urobíš s papierom, ktorý má jednu stranu čistú?|Najprv pokreslím aj čistú stranu.|Najprv ho vyhodím do triedeného papiera.|Najprv si vezmem nový list a tento odložím bokom.|Opätovné využitie vecí znižuje množstvo odpadu.
Mravenisko si všimneš pri chodníku. Ako zistíš, čo mravce robia, bez poškodenia ich domova?|Pozorujem ich na povrchu z odstupu.|Odkryjem vrchnú vrstvu a potom ju vrátim.|Vložím dnu konárik a sledujem ho.|Aj malé odkrytie alebo zásah narúša mravenisko. Na pozorovanie netreba jeho domov rozoberať.
@2|civil
Ako zavoláš priamo hasičov na Slovensku?|150.|155.|158.|Na čísle 150 sa dovoláš hasičom; pri núdzi môžeš volať aj 112.
Pri požiari v škole si zabudol bundu. Čo urobíš?|Pokračujem s triedou na zhromaždisko.|Vrátim sa po ňu, ak už pri dverách nevidím dym.|Poprosím staršieho žiaka, aby ju vyzdvihol.|Pri evakuácii má bezpečnosť prednosť pred vecami.
Rieka po silnom daždi zaplaví ulicu. O akú udalosť ide?|Povodeň.|Požiar.|Priemyselnú haváriu.|Pri povodni sa voda dostane na územie, ktoré bežne nezaplavuje. Ide o prírodné ohrozenie.
Čo urobíš s poškodenou elektrickou zásuvkou?|Nedotýkam sa jej a oznámim poruchu.|Prekryjem ju papierom, aby ju nikto nevidel.|Skúsim, či druhá dierka funguje bezpečnejšie.|Elektrické zariadenia môže bezpečne opravovať odborník.
Pri zápachu plynu doma…|nedotýkam sa vypínačov a odídem s dospelým.|najprv zapnem odsávanie a potom to oznámim.|najprv zhasnem všetky svetlá a potom vyjdem von.|Iskra alebo plameň môžu zapáliť unikajúci plyn; pomoc sa volá z bezpečia.
Čo znamená zelená značka bežiacej postavy a šípky?|Smer úniku.|Zhromaždisko.|Stanovište prvej pomoci.|Značky úniku pomáhajú pri opúšťaní budovy.
Na čo slúži cvičný požiarny poplach?|Na nácvik cesty a pokynov pri opúšťaní budovy.|Na skúšku, kto sa dostane k bráne najrýchlejšie.|Na zistenie, kto si zapamätal polohu hasiaceho prístroja.|Nácvik pomáha vedieť, čo robiť pri skutočnom ohrození.
Učiteľ kontroluje žiakov po evakuácii. Prečo?|Aby zistil, či sa všetci dostali do bezpečia.|Aby zistil, kto nechal tašku v šatni.|Aby rozhodol, kto smie odísť bez ďalších pokynov.|Kontrola počtu je dôležitá pre bezpečnosť triedy.
Pri rieke stúpla voda a zaplavila okraj chodníka. Ktorú cestu zvolíte s učiteľom?|Vyznačenú obchádzku ďalej od rieky.|Zaplavený chodník, ak vidno jeho okraj.|Kratšiu cestičku tesne pod brehom.|Nebezpečné môžu byť prúd aj podmyté brehy. Zaplavený chodník neprechádzame ani vtedy, keď vidno jeho okraje.
Keď počuješ varovnú sirénu na školskom dvore…|vyhľadám učiteľa a počúvam ďalšie pokyny.|idem ku školskej bráne čakať na rodiča.|počkáme s kamarátmi, či začnú odchádzať aj iné triedy.|Nebezpečenstvo nemusí byť hneď viditeľné.
@2|aid
Po pobyte vo vysokej tráve je dobré…|s dospelým prezrieť telo a skontrolovať oblečenie.|skontrolovať topánky a ostatné nechať na ráno.|pozrieť len miesta, ktoré ma práve svrbia.|Včasné nájdenie a správne odstránenie kliešťa je dôležité.
Prisaje sa ti kliešť. Čo urobíš?|Poviem to dospelému, aby pomohol s odstránením.|Počkám do rána, či kliešť neodpadne sám.|Prekryjem ho náplasťou a zatiaľ to neoznámim.|Dospelý pomôže kliešťa bezpečne odstrániť; ničím ho nepotieraj.
Po uštipnutí osou sa kamarátovi ťažko dýcha. Čo urobíš?|Hneď privolám dospelého a voláme 155.|Najprv ochladíme iba miesto vpichu a počkáme.|Najprv ho nechám prejsť sa, či sa mu nebude dýchať lepšie.|Ťažké dýchanie po uštipnutí môže znamenať vážnu reakciu.
Ktoré oblečenie je vhodné do dažďa?|Vodu odpudzujúca vrstva a vhodná obuv.|Hrubý bavlnený sveter a ľahká obuv.|Dve bavlnené tričká a otvorené topánky.|Vhodné oblečenie pomáha predísť premoknutiu a prechladnutiu.
Ako si zakryješ ústa pri kašli?|Lakťovou jamkou alebo vreckovkou.|Dlaňou, ktorou potom chytím spoločnú kľučku.|Otočením hlavy nabok bez zakrytia úst.|Kašeľ do lakťovej jamky obmedzí šírenie kvapôčok.
Prečo si pred ošetrením malej ranky umývame ruky?|Aby sme do rany nepreniesli nečistoty.|Aby sa rana po nalepení náplasti rýchlejšie ochladila.|Aby obväz nebolo potrebné po zašpinení vymeniť.|Čistota pomáha chrániť ranu pred infekciou.
Ako sa správaš v čakárni u lekára?|Čakám pokojne a kašeľ si zakrývam.|Presadám si k chorým, aby som zistil, čo im je.|Požičiavam ostatným vlastnú fľašu na pitie.|Pokoj a ohľaduplnosť pomáhajú chorým aj zdravotníkom.
Na slnečnom výlete je vhodné…|priebežne piť a robiť prestávky v tieni.|vypiť veľa až na konci a dovtedy pokračovať.|spoliehať sa na čiapku a piť až pri veľkom smäde.|Pitný režim, tieň a pokrývka hlavy pomáhajú predísť prehriatiu.
Kamarátovi tečie krv z nosa. Aká poloha je vhodná?|Sed s miernym predklonom.|Sed s miernym záklonom.|Ľah s tvárou otočenou nahor.|Pri predklone krv nepreteká do hrdla; zavolaj dospelého.
Po uštipnutí hadom na výlete…|ostanem v pokoji, obmedzím pohyb a privolám pomoc.|vykročím rýchlo ku škole, aby som bol skôr pri pomoci.|silno stiahnem miesto nad ranou a pokračujem v chôdzi.|Obmedz pohyb a privolaj 155 alebo 112; ranu nerež ani nevysávaj.
@2|orientation
Turistická značka na strome ukazuje…|Vyznačenú turistickú trasu.|Náročnosť každého úseku podľa farby.|Najkratšiu cestu k najbližšej obci.|Turistické značenie pomáha sledovať trasu.
Pozeráš sa na sever. Otočíš sa celkom opačne. Kam teraz pozeráš?|Na juh.|Na východ.|Na západ.|Otočenie opačným smerom je polovička celého otočenia. Oproti severu leží juh.
Ktorá pomôcka pomáha nájsť sever?|Kompas.|Výškomer.|Krokomer.|Označený severný koniec strelky kompasu smeruje približne na sever.
Na rázcestí s učiteľom hľadáš cestu. Čo použijete?|Porovnáme smerovník s plánovanou trasou.|Vyberieme najširší chodník, aj keď má inú značku.|Pôjdeme smerom, ktorým ide najviac turistov.|Smerovník uvádza ciele a smer značených trás.
[map] Najprv ideš zo školy nadol k rieke. Ak sa vraciaš tou istou cestou, ktorým smerom po obrázku ideš?|Nahor ku škole.|Doprava k lesu.|Nadol od školy.|Návrat po rovnakej ceste vedie opačným smerom než cesta od školy.
Slnko vychádza približne na…|východe.|západe.|juhu.|Východ slnka je približná pomôcka, jeho presná poloha sa počas roka mení.
Slnko zapadá približne na…|západe.|východe.|severe.|Podľa západu slnka vieme svetové strany určiť len približne.
Čo si overíme pred výletom?|Trasu a počasie na čas výletu.|Trasu a počasie zo včerajšieho rána.|Počasie pri škole bez kontroly cieľa výletu.|Trasu aj vybavenie prispôsobíme predpovedi počasia.
Prečo na chodníku sledujeme značky?|Aby sme sledovali zvolenú trasu aj na rázcestiach.|Aby sme mohli vynechať dohodnuté čakanie skupiny.|Aby sme mali istotu, že každá značka vedie do našej obce.|Značky sledujeme spolu s mapou a pokynmi vedúceho.
Ak sa na výlete unavíš, čo je rozumné?|Poviem učiteľovi o únave, kým som pri skupine.|Spomalím bez oznámenia, skupinu neskôr dobehnem.|Posadím sa za zákrutou, učiteľ si chýbanie všimne.|O únave treba povedať skôr, než sa od skupiny oddelíš.
@2|nature
Môžeš piť vodu z ľubovoľného potoka?|Nie, aj číra voda môže byť znečistená.|Áno, ak voda rýchlo tečie cez kamene.|Áno, ak je potok ďaleko od viditeľných budov.|Voda môže obsahovať neviditeľné znečistenie.
Ktoré huby môže dieťa ochutnávať priamo v lese?|Žiadne neznáme ani surové huby.|Huby, z ktorých už odhryzol slimák.|Huby, ktoré majú príjemnú vôňu.|Jedlosť huby neurčujeme podľa farby ani veľkosti.
Voľne žijúce zviera sa nebojí ľudí. Čo urobíš?|Nepribližujem sa a upozorním dospelého.|Podídem bližšie, ak sa nehýbe prudko.|Ponúknem vodu z ruky, keď vyzerá unavené.|Nezvyčajné správanie zvieraťa môže mať viac príčin; drž si odstup.
Ktorá nádoba obvykle slúži na papier?|Modrá nádoba.|Žltá nádoba.|Zelená nádoba.|Pri triedení sa vždy riaď aj označením miestnej nádoby.
Prečo ostávame na vyznačenom chodníku?|Chránime porast pred poškodením a ušliapaním.|Mimo chodníka býva pôda vždy hlbšia než na chodníku.|Farba značky určuje, ktoré rastliny sa smú pošliapať.|Zošliapavanie mimo chodníka poškodzuje porast a pôdu.
Čo urobíš s prázdnou fľašou, keď nikde nie je kôš?|Odnesiem ju so sebou k vhodnému zberu.|Položím ju ku smerovníku, kde ju niekto ľahko nájde.|Nechám ju otvorenú pri strome, aby sa naplnila dažďom.|Chýbajúci kôš nie je dôvod nechať odpad v prírode.
Ako môžeš pomôcť vtákom bez rušenia hniezda?|Vtáky si pozriem ďalekohľadom z diaľky.|K hniezdu položím misku jedla a čakám pri ňom.|Na konár s hniezdom zavesím zvonček proti mačkám.|Najlepšie je nezasahovať do hniezdenia.
Čo urobíš, keď v lese nájdeš striekačku?|Nedotýkam sa jej a označím miesto dospelému slovne.|Zdvihnem ju cez papier a odnesiem učiteľovi.|Posuniem ju topánkou ku košu na odpad.|Ostrý neznámy odpad môže byť nebezpečný.
Ako sa správaš pri mravcoch na chodníku?|Bezpečne ich obídem bez zasahovania.|Prenesiem ich na listoch na iné miesto.|Prestavím im cestu kamienkami, aby šli do trávy.|Malé živočíchy zbytočne nerušíme.
Ktorá desiata vytvorí menej jednorazového odpadu?|Desiata v opakovane použiteľnej krabičke.|Desiata každý deň v novom papierovom vrecku.|Desiata v novom obale označenom ako recyklovateľný.|Krabičku môžeme umyť a použiť znova.
@3|civil
Ako sa volá organizovaný odchod z ohrozeného miesta?|Evakuácia.|Ukrytie.|Hygienická očista.|Evakuácia presúva ľudí z ohrozeného priestoru do bezpečia.
Čo pri volaní na 112 oznámiš medzi prvými údajmi?|Miesto udalosti a stručne, čo sa stalo.|Meno zraneného a jeho rozvrh vyučovania.|Vlastné meno a opis cesty, ktorou som prišiel.|Presné miesto pomáha záchranárom dostať sa k udalosti.
V obci veľmi prudko prší, ale rieka ešte nie je plná. Môže sa zatopiť podchod?|Áno, voda sa tam môže nahromadiť aj bez vyliatia rieky.|Nie, podchody zaplavuje až voda z vyliatej rieky.|Nie, ak má podchod aspoň jeden kanálový vpust.|Prívalová voda sa zhromažďuje aj mimo riek. Kanalizácia ju nemusí stihnúť odviesť.
Pri kontrole na zhromaždisku si všimneš, že chýba spolužiak. Čo urobíš bez odkladu?|Oznámim učiteľovi, koho som naposledy videl a kde.|Pošlem spolužiaka späť, kým učiteľ počíta triedu.|Počkám do konca kontroly všetkých tried a až potom to poviem.|Informáciu o chýbajúcom spolužiakovi oznám hneď. Hľadanie v ohrozenej budove prenechaj záchranárom.
Čo je bezpečné pri búrke na školskom dvore?|Ísť s učiteľom do uzavretej školskej budovy.|Počkať pod strechou otvoreného prístrešku.|Postaviť sa k stene zvonka a zostať na dvore.|Pevná uzavretá budova poskytuje lepší úkryt pred búrkou.
Pri škole uniká silný neznámy zápach zo skladu. Čo považuješ za varovný znak?|Nezvyčajný zápach, ktorý treba oznámiť dospelému.|To, že sklad nemá okná otočené ku škole.|To, že sa pri sklade pravidelne zastavuje dodávka.|Nezvyčajný zápach môže signalizovať únik. Žiak ho neskúma zblízka; upozorní dospelého.
Čo znamená dvojminútový kolísavý tón sirény?|Všeobecné ohrozenie.|Ohrozenie vodou.|Koniec ohrozenia.|Všeobecné ohrozenie sa oznamuje kolísavým tónom trvajúcim dve minúty.
Kde získaš pokyny po varovnom signáli?|Z aktuálneho oficiálneho hlásenia a od učiteľa.|Z posledného uloženého hlásenia, aj keď je z iného dňa.|Od spolužiaka, ktorý pozná podobnú udalosť z televízie.|Pokyny musia zodpovedať aktuálnej udalosti a miestu.
Cez cestu leží spadnutý elektrický kábel. Čo urobíš?|Zostanem ďaleko a upozorním dospelého.|Prejdem popri ňom, ak sa vodiča nedotknem.|Prekročím ho v topánkach s gumovou podrážkou.|Kábel aj jeho okolie môžu byť pod napätím.
Pri poplachu používa trieda schody. Ako pôjdeš?|Pokojne, s triedou a bez blokovania schodov.|Po dvoch schodoch, aby bola cesta skôr voľná.|Postavím sa pri zábradlí a nechám celú školu predísť.|Priechodné schody a pokojný pohyb obmedzujú riziko pádu.
@3|aid
Ako si bezpečne chrániš chrup?|Zuby si pravidelne čistím vhodnou kefkou.|Po jedle si iba vypláchnem ústa vodou.|Čistenie nahradím žuvačkou bez cukru.|Pravidelná starostlivosť pomáha chrániť zuby aj ďasná.
Kedy je dôležité umyť si ruky?|Po toalete a pred jedlom aj bez viditeľnej špiny.|Pred jedlom, len keď sú ruky viditeľne špinavé.|Po toalete stačí ruky utrieť do čistého uteráka.|Mikróby nevidíme voľným okom.
Malú odreninu treba pred prekrytím…|opláchnuť čistou tečúcou vodou.|najprv prekryť a vodou opláchnuť až náplasť.|utrieť suchou vreckovkou a hneď prekryť.|Pri malej odrenine čistá voda odstráni nečistoty; pomôže dospelý.
Obviazaný prst tŕpne a bledne. Čo urobíš?|Poviem dospelému, že obväz môže tlačiť.|Počkám, kým si prst na tlak zvykne.|Pridám vrstvu obväzu, aby prst zostal v teple.|Príliš tesný obväz môže obmedziť prekrvenie prsta.
Po krátkom spánku si na výlete unavený a robíš chyby. Čo z toho vyplýva?|Spánok ovplyvňuje aj pozornosť a bezpečné rozhodovanie.|Spánok ovplyvňuje svaly, pozornosť na výlete nezmení.|Spánok sa dá na celý deň nahradiť sladkým nápojom.|Nedostatok spánku môže zhoršiť sústredenie. Únavu treba povedať dospelému a prispôsobiť jej činnosť.
Kamarátovi sa dostal prach do oka. Čo je vhodné?|Netrieť oko a požiadať dospelého o pomoc.|Pretrieť oko čistou vreckovkou pod viečkom.|Nechať kamaráta fúknuť priamo do oka.|Šúchanie môže oko podráždiť; dospelý pomôže s bezpečným vypláchnutím.
Na výlete je ti slabo z horúčavy. Čo urobíš?|Oznámim to a odpočiniem si v tieni.|Napijem sa a pokračujem bez prestávky.|Zložím čiapku a zrýchlim ku skupine.|Treba prerušiť námahu, ochladiť sa a sledovať stav.
Kedy môžeš užiť liek?|Keď ho podľa pokynov podá zodpovedný dospelý.|Keď má spolužiak podobné príznaky a jeho liek mu pomohol.|Keď si pamätám farbu lieku z minulého ochorenia.|Lieky sa užívajú podľa správneho dávkovania a pokynov.
Ako pomôžeš kamarátovi s poraneným lakťom?|Privolám dospelého a nechám lakeť v pokoji.|Pomôžem mu lakeť rozhýbať, aby nestuhol.|Skúsim, či ho bolí aj pri úplnom vystretí.|Bolestivú končatinu zbytočne nezaťažujeme.
Potrebuješ priamo zdravotnú záchrannú službu. Ktoré číslo vyberieš?|155.|150.|158.|Číslo 155 patrí zdravotnej záchrannej službe; 150 hasičom a 158 polícii.
@3|orientation
Ktorá skupina obsahuje iba hlavné svetové strany?|Sever, východ, juh, západ.|Sever, severovýchod, juh, západ.|Sever, východ, juhovýchod, západ.|Hlavné strany sú štyri. Severovýchod a juhovýchod sú vedľajšie svetové strany.
Stojíš tvárou na sever a otočíš sa doprava. Kam sa pozeráš?|Na východ.|Na západ.|Na juh.|Pravá strana pri pohľade na sever je východ. Celé otočenie na opačnú stranu by viedlo na juh.
Stojíš tvárou na východ. Ktorý smer máš za chrbtom?|Západ.|Sever.|Juh.|Východ a západ sú protiľahlé svetové strany, rovnako ako sever a juh.
[map] Zo školy ideš k lesu a rovnakou cestou späť. Aké smery sa vystriedajú?|Východ a potom západ.|Západ a potom východ.|Sever a potom juh.|Les leží východne od školy. Pri návrate sleduješ opačný smer, teda západ.
Čo je údolie?|Nižší priestor medzi svahmi.|Znížené miesto medzi dvoma vrcholmi na hrebeni.|Horný okraj svahu pozdĺž hrebeňa.|Údolím často preteká potok alebo rieka.
Čo je úpätie kopca?|Spodná časť kopca pri okolitej krajine.|Znížené miesto medzi dvoma vrcholmi.|Najvyšší bod na dlhom hrebeni.|Úpätie je miesto pri spodnej časti svahu.
Čo označuje legenda mapy?|Význam značiek použitých na mape.|Vzdialenosť každého bodu od začiatku trasy.|Smer, ktorým je mapa natočená v ruke.|Značky čítame podľa legendy konkrétnej mapy.
Ako na Slovensku približne smeruje tieň na pravé slnečné poludnie?|Na sever.|Na juh.|Na západ.|Slnko je vtedy približne na juhu, tieň smeruje opačne; nejde vždy o 12:00 na hodinách.
Čo je vhodný stály orientačný bod v obci?|Veža, ktorú viem nájsť aj na pláne obce.|Zastavený školský autobus pri chodníku.|Otvorený stánok, ktorý sa presúva po námestí.|Výrazná budova pomáha aj pri opakovanom hľadaní cesty.
Ak na trase chýba značenie a nie si si istý…|zastavíme sa spolu a porovnáme okolie s mapou.|vyberieme vetvu chodníka s väčším počtom stôp.|pôjdeme ďalej, kým sa neobjaví akákoľvek značka.|Neistotu riešime skôr, než sa vzdialime od známeho miesta.
@3|nature
Čo znamená chránené územie?|Územie s osobitnými pravidlami ochrany.|Územie, kde sú pravidlá rovnaké ako na každom ihrisku.|Územie, kde sa chránia iba veľké živočíchy.|Chránené územia uchovávajú cenné prírodné hodnoty.
Ako si odnesieš spomienku na chránený kvet?|Fotografiou z povoleného chodníka.|Jediným odtrhnutým kvetom bez koreňa.|Presadením jednej malej rastliny do záhrady.|Fotografia ponechá rastlinu aj jej prostredie nedotknuté.
Prečo netrháme kôru zo živého stromu?|Kôra chráni strom pred poškodením.|Kôra nahrádza listy pri zachytávaní dažďovej vody.|Kôra slúži najmä na odhad veku stromu.|Poškodenie kôry môže strom oslabiť.
Po desiate ostal papierový obrúsok a šupka z ovocia. Čo môžeš odhodiť do potoka?|Ani jedno, oba zvyšky odnesiem.|Šupku, lebo je prírodná.|Obrúsok, lebo sa vo vode rozmočí.|Aj rozložiteľné zvyšky nepatria do potoka. Môžu meniť prostredie a lákať zvieratá.
Čo znamená opätovné použitie?|Použiť tú istú vec znovu na vhodný účel.|Spracovať starý materiál na nový výrobok.|Roztriediť obaly do farebných nádob.|Opätovné používanie šetrí materiál a znižuje odpad.
Prečo sú včely a iné opeľovače dôležité?|Prenášajú peľ medzi kvetmi mnohých rastlín.|Prenášajú ku koreňom rastlín zásoby vody.|Odstraňujú zo všetkých kvetov škodlivý peľ.|Prenos peľu je dôležitý pri rozmnožovaní mnohých rastlín.
Nájdeš zraneného ježa. Čo urobíš?|Požiadam dospelého o kontaktovanie odbornej pomoci.|Podám mu mlieko a počkám na zlepšenie.|Odnesiem ho hlbšie do lesa, kde bude mať pokoj.|Voľne žijúce zranené zviera má posúdiť odborník.
Čím najlepšie znížime odpad pri pití na výlete?|Používaním vlastnej znovu naplniteľnej fľaše.|Nákupom malej novej fľaše na každú prestávku.|Vhadzovaním nových fliaš do koša po každom napití.|Znovupoužiteľná fľaša obmedzí jednorazové obaly.
Prečo neodhadzujeme ohryzok jablka pri chodníku?|Môže prilákať zvieratá k turistickému chodníku.|Prírodné zvyšky sa v lese vôbec nerozkladajú.|Každé ovocie je pre všetky lesné zvieratá jedovaté.|Zvyšky desiaty si odnášame, aj keď sú rozložiteľné.
Ako sa správaš pri informačnej tabuli rezervácie?|Overím si pravidlá ešte pred pokračovaním.|Pravidlá si prečítam až pri návrate z trasy.|Riadim sa správaním ostatných, ktorí tabuľu obišli.|Miestne pravidlá chránia návštevníkov aj prírodu.
@4|civil
Na obale čistiaceho prípravku je výstražný symbol. Čo znamená?|Označuje konkrétny druh nebezpečenstva látky.|Označuje odporúčanú silu dávky pri čistení.|Označuje, do ktorého koša patrí celý obsah fľaše.|Výstražné symboly upozorňujú na vlastnosti látky a riziká.
Úrady pri úniku látky vonku prikážu ukrytie v budove. Čo urobíte?|Zatvoríme okná a obmedzíme prívod vzduchu podľa pokynov.|Otvoríme okná na opačnej strane než viditeľný únik.|Zapneme ventilátor privádzajúci vzduch, aby sa látka zriedila.|Obmedzenie prívodu vonkajšieho vzduchu znižuje prenikanie škodlivín.
Čo znamená hygienická očista po znečistení?|Odstránenie znečistenia z tela určeným postupom.|Presun ľudí do čistej miestnosti bez ďalších krokov.|Zakrytie znečisteného odevu ďalšou vrstvou oblečenia.|Spôsob očisty závisí od látky; riaď sa pokynmi záchranárov.
Spolužiak chce pri úniku neznámeho plynu vyjsť von s vreckovkou cez ústa. Čo mu povieš?|Vreckovka nenahrádza určenú ochranu, zostaň pri pokynoch dospelých.|Vlhká vreckovka postačí, ak sa vonku zdržíš len krátko.|Dve vrstvy vreckovky postačia, keď už plyn nevidno.|Bežná látka neposkytuje spoľahlivú ochranu pred nebezpečnými plynmi. Ani neprítomnosť viditeľného oblaku neznamená bezpečie.
Čo patrí do pripraveného evakuačného batohu?|Voda, potrebné lieky a doklady podľa plánu.|Veľká zásoba jedla bez vody a potrebných liekov.|Náhradné oblečenie bez informácií a liekov, ktoré potrebujem.|Evakuačný batoh má obsahovať nevyhnutné veci a má sa dať uniesť.
Šesťminútový stály tón sirény znamená…|ohrozenie vodou.|všeobecné ohrozenie.|koniec ohrozenia.|Tento signál varuje pred ničivými účinkami vody.
Pri ohrození povodňou je vhodné…|ísť určenou bezpečnou trasou mimo záplavy.|zvoliť skratku cez podchod, kým v ňom voda siaha len po členky.|čakať pri brehu na presnejší odhad výšky hladiny.|Pri vode vyhľadávame bezpečie mimo nízko položených zaplavovaných miest.
Prečo sa nehráme v blízkosti skladu chemikálií?|Aj neviditeľný únik môže predstavovať riziko.|Plot zachytí všetky pary, riziko je len za ním.|Plyny sú rizikové až vtedy, keď majú viditeľnú farbu.|Rešpektuj oplotenie a výstražné označenia.
Nájdeš neznámu kvapalinu v neoznačenej fľaši. Čo urobíš?|Nemanipulujem s ňou a oznámim nález.|Privoňam si z malej vzdialenosti a potom ju odložím.|Podľa farby určím obsah a prelejem ho do označenej nádoby.|Neznámu látku neochutnávame ani neskúšame vdychovať.
Po evakuácii sa môžeš vrátiť do budovy…|až po povolení zodpovedných osôb.|keď sa už siréna niekoľko minút neozýva.|keď cez okno vidím, že na chodbe nikto nie je.|Skryté nebezpečenstvo môže trvať aj po zdanlivom upokojení situácie.
@4|aid
Aká je úloha srdca?|Pumpuje krv do ciev a udržiava jej obeh.|Privádza vzduch priamo do pľúc pri nádychu.|Čistí vdychovaný vzduch pred vstupom do pľúc.|Srdce pumpuje krv, ktorá prenáša kyslík a živiny.
Na čo slúžia pľúca?|Na výmenu kyslíka a oxidu uhličitého.|Na pumpovanie okysličenej krvi do končatín.|Na rozvod prijatých živín do svalov.|Dýchanie privádza do tela kyslík.
Ako sa dajú obmedziť niektoré infekcie?|Umývaním rúk aj bez viditeľnej špiny a zakrývaním kašľa.|Umývaním rúk iba po kontakte s viditeľnou špinou.|Častou výmenou uterákov, ktoré si všetci požičiavame.|Hygiena pomáha prerušiť prenos pôvodcov chorôb.
Pri obväzovaní kolena má čisté krytie…|ležať čistou stranou na vyčistenej rane.|najprv sa navlhčiť slinami, aby lepšie držalo.|pred priložením sa utrieť o čisté oblečenie.|Časť krytia, ktorá sa dotýka rany, musí zostať čistá.
Z rany silno vyteká krv a spolužiak slabne. Dospelý je pri vás. Čo je potrebné?|Bezodkladne privolať 155 a začať zastavovať krvácanie.|Najprv ranu dôkladne umyť a až potom posúdiť volanie.|Najprv zistiť, či rodičia súhlasia s privolaním záchranárov.|Silné krvácanie vyžaduje rýchly tlak na ranu a tiesňové volanie. Čakanie na rodičov ani umývanie nesmú pomoc zdržať.
Čím môžeme zastaviť krvácanie z rany bez zapichnutého predmetu?|Pevným priamym tlakom cez krytie.|Častým nadvihovaním krytia a kontrolou rany.|Jemným prikladaním náplasti bez tlaku.|Pri silnom krvácaní tlačíme na ranu a privolávame pomoc.
Popálené miesto od horúcej vody sa ochladzuje…|chladnou tečúcou vodou aspoň 20 minút.|studeným obkladom na minútu, kým klesne bolesť.|krémom po krátkom opláchnutí pod kohútikom.|Chladíme postihnuté miesto vodou, ostatné telo chránime pred chladom.
Kamarát je po páde na koleno zranený. Čo mu povieš?|Zostaň v pokoji, zavolám dospelého.|Skús sa prejsť, podľa chôdze spoznáme vážnosť.|Najprv koleno viackrát ohni, aby neopuchlo.|Poranenie treba posúdiť a bolestivú nohu nezaťažovať.
Čo urobíš s neporušeným pľuzgierom po popálení, keď už je miesto ochladené?|Neprepichujem ho a ukážem ho dospelému.|Prepichnem ho čistou ihlou, aby povolil tlak.|Odstránim vrchnú kožu, aby sa krytie dotklo rany.|Pľuzgier neprepichujeme ani neodstraňujeme jeho kožu; tým by sa zvýšilo riziko infekcie.
Prečo pri ošetrovaní používame jednorazové rukavice, ak sú poruke?|Znižujú kontakt s krvou pri ošetrení.|Umožňujú dotýkať sa sterilného krytia kdekoľvek.|Nahrádzajú umytie rúk po ošetrení.|Rukavice chránia ošetrujúceho aj zraneného, ale nenahrádzajú ďalšiu pomoc.
@4|orientation
Na mape je modrá prerušovaná čiara, ktorej význam nepoznáš. Čo urobíš?|Overím jej presný význam v legende.|Určím ju ako rieku len podľa modrej farby.|Určím ju ako chodník len podľa prerušovania.|Farba aj tvar čiary majú význam podľa konkrétnej mapy. Neznámu značku overujeme v legende.
Čo znamená nadmorská výška vrcholu 800 m?|Vrchol je 800 metrov nad hladinou mora.|Od úpätia na vrchol treba vystúpať presne 800 metrov.|Trasa od najbližšej obce po vrchol meria 800 metrov.|Nadmorská výška sa vzťahuje na referenčnú hladinu mora.
[map] Stojíš pri škole a pozeráš sa k stanu. Kde máš les?|Po pravej ruke.|Po ľavej ruke.|Za chrbtom.|Pozeráš sa na sever. Východ, kde leží les, je pri tomto otočení napravo.
Ktorá dvojica obsahuje iba susedov Slovenska?|Poľsko a Maďarsko.|Slovinsko a Maďarsko.|Poľsko a Rumunsko.|So Slovenskom susedia Poľsko, Ukrajina, Maďarsko, Rakúsko a Česko. Slovinsko ani Rumunsko spoločnú hranicu nemajú.
Ako sa na bežnej mape overí smer severu?|Podľa severovej šípky a orientácie mapy.|Podľa horného okraja obrázka aj po otočení mapy.|Podľa smeru čítania najväčšieho nápisu na mape.|Sever býva hore, ale vždy si to over podľa mapy.
Na čo slúži jednoduchý náčrt trasy?|Na zachytenie odbočiek a dôležitých bodov.|Na presné určenie vzdialeností aj bez mierky.|Na potvrdenie priechodnosti trasy v každom počasí.|Náčrt pomáha predstaviť si postup a orientačné body.
Na mape je most cez rieku. Čo to môže znamenať pre trasu?|Miesto možného prechodu, ktorého stav treba overiť.|Potvrdenie bezpečného prechodu aj po povodni.|Záruku, že všetky blízke brehy sú vhodné na brodenie.|Mapa nenahrádza posúdenie aktuálneho stavu mosta.
Škola je vo výške 480 m a cieľ na kopci vo výške 620 m. Aký je rozdiel výšok?|140 m.|240 m.|1 100 m.|Rozdiel nadmorských výšok je 620 − 480 = 140 m. Nehovorí však, aká dlhá je cesta.
Kedy je odhad vzdialenosti najlepšie overiť meraním na mape?|Pred rozhodnutím, či plánovanú trasu zvládneme.|Keď je cieľ v dohľade, meranie už netreba.|Až keď počas chôdze prekročíme plánovaný čas.|Odhad sa môže mýliť, preto plán dopĺňame meraním a údajmi o trase.
Ktorý smer je medzi severom a východom?|Severovýchod.|Severozápad.|Juhovýchod.|Vedľajšie svetové strany ležia medzi hlavnými.
@4|nature
Čo pomáha udržať vzduch v obci čistejší?|Bezpečná chôdza namiesto krátkej jazdy autom.|Chod stojaceho auta naprázdno, aby sa nemuselo znovu štartovať.|Jazda autom namiesto chôdze aj na jednu krátku ulicu.|Menej zbytočných jázd môže znížiť miestne emisie.
Prečo sa plasty nespaľujú v ohnisku?|Pri spaľovaní môžu vznikať škodlivé látky.|Problémom je iba zápach, ktorý vietor úplne odstráni.|Malé množstvo plastu zhorší iba vzhľad ohniska.|Odpad nepatrí do ohniska ani domáceho spaľovania.
Ako dospelý bezpečne opustí povolené ohnisko?|Uhasí ho a overí, že nezostali žeravé miesta.|Zaleje viditeľné plamene a hneď odíde.|Rozhrnie uhlíky, aby sa rýchlejšie ochladili bez kontroly.|Aj skryté žeravé uhlíky môžu neskôr zapáliť okolie.
Prečo sa v lese staráme o čistotu?|Aj malé zvyšky môžu zvieratá ohroziť alebo prilákať.|Rizikové sú iba kusy odpadu väčšie ako zviera.|Odpad škodí zvieratám len vtedy, keď zapácha.|Odpadky môžu byť pascou alebo nebezpečnou potravou.
Ktoré prikrmovanie vtákov je vhodné?|Vhodné krmivo a pravidelne čistené kŕmidlo.|Čerstvé slané pečivo v čistenom kŕmidle.|Vhodné semienka pridávané na staré plesnivé zvyšky.|Nevhodné a pokazené krmivo môže vtákom uškodiť.
Prečo má význam voda zadržaná v krajine?|Spomaľuje odtok a zostáva dostupná rastlinám.|Čím rýchlejšie odtečie z pôdy, tým menej rastliny vysychajú.|Voda v pôde pomáha iba v deň, keď prší.|Pôda a vegetácia pomáhajú udržať vodu v krajine.
Na výlete je tabuľa so zákazom vstupu kvôli ochrane prírody. Čo urobíš?|Zvolím povolenú trasu, aj keď je dlhšia.|Prejdem zákaz, ak pôjdem potichu a sám.|Obídem tabuľu po okraji toho istého územia.|Uzávery môžu chrániť citlivé miesta alebo živočíchy.
Čo je vhodné pri pozorovaní lesného zvieraťa?|Zostať v odstupe a použiť ďalekohľad.|Približovať sa pomaly, kým zviera nezačne utekať.|Prilákať ho jedlom a potom ho pozorovať zblízka.|Pozorovanie nemá meniť prirodzené správanie zvieraťa.
Ako triedime prázdny obal?|Podľa materiálu a pravidiel miestneho zberu.|Podľa najväčšej farby na jeho potlači.|Podľa výrobku, ktorý v ňom bol, bez čítania označenia.|Pravidlá niektorých zberov sa môžu medzi obcami líšiť.
Čo urobíš s odpadom pri spoločnom čistení okolia školy?|Bežný odpad zbieram s pomôckami, neznámy hlásim.|Neznáme fľaše uzatvorím a odložím do tašky.|Ostré predmety zabalím do papiera a nosím vo vrecku.|Bezpečnosť je dôležitá aj pri ochrane prírody.
@5|civil
Siréna dve minúty mení výšku tónu. Hlásenie ešte neodznelo. Čo už vieš?|Ide o všeobecné ohrozenie, konkrétne pokyny ešte treba vypočuť.|Ide o ohrozenie vodou, treba okamžite vybrať najbližší kopec.|Ide o koniec ohrozenia, do budovy sa už možno bezpečne vrátiť.|Kolísavý dvojminútový tón označuje všeobecné ohrozenie. Samotný tón neurčuje konkrétnu bezpečnú trasu ani všetky potrebné kroky.
Rodina pripravila batoh, ktorý najmladší člen neunesie. Aká úprava dáva zmysel?|Ponechať potrebné veci a primerane rozdeliť záťaž.|Pridať zásoby, aby sa nikto nemusel vracať domov.|Zabaliť všetko do jednej veľkej tašky pre najmladšieho.|Batožina má umožniť rýchly presun. Obsah aj rozdelenie záťaže treba prispôsobiť členom rodiny.
Čo je kolektívna ochrana obyvateľstva?|Spoločné ukrytie a organizovaná evakuácia.|Ochranné rukavice a maska správnej veľkosti.|Osobný pršiplášť a uzavretá ochranná obuv.|Kolektívne opatrenia chránia skupiny ľudí.
Pri úniku látky úrady určia bezpečnú evakuačnú trasu. Čo spravíš?|Použijem vyhlásenú trasu podľa pokynov.|Zvolím kratšiu trasu, keď na nej nevidno oblak.|Zvolím obvyklú cestu, ak na nej zatiaľ necítim zápach.|Skratka môže viesť priamo ohrozeným miestom.
Ktoré informácie sú pri tiesňovom hovore užitočné?|Miesto a priebeh udalosti, postihnutí a riziká.|Najprv vlastný odhad príčiny, miesto doplním neskôr.|Najprv mená svedkov, potom ich odhady závažnosti.|Operátor potrebuje miesto, situáciu a doplňujúce údaje, na ktoré sa pýta.
Dym pri škole zmizol, ale návrat zatiaľ nikto nepovolil. Čo urobíš?|Zostanem na určenom mieste a čakám na pokyn.|Vrátim sa po veci, keď už budova vyzerá pokojne.|Požiadam kamaráta pri vchode, aby bezpečnosť odhadol.|Ústup dymu sám nepotvrdzuje bezpečnosť budovy. Návrat povoľujú zodpovedné osoby.
Prečo pri evakuácii nepoužijeme bežný výťah?|Výťah sa môže zastaviť alebo zaplniť dymom.|Bežný výťah je bezpečný, pokiaľ svieti jeho displej.|Výťah je pri poplachu vhodný, ak sa odvezie iba jeden človek.|Použijeme určené únikové cesty podľa plánu budovy.
Čo urobíš pri signáli ohrozenie vodou?|Sledujem hlásenie a vyhnem sa zaplavovaným miestam.|Použijem rovnaký pivničný úkryt ako pri každom poplachu.|Vyberiem najkratšiu cestu bez ohľadu na polohu pri rieke.|Pri povodni sa bezpečný postup líši od ukrytia pred nebezpečnou látkou.
Aké potraviny sú vhodné do núdzovej zásoby?|Trvanlivé potraviny použiteľné aj bez varenia.|Trvanlivé jedlá vyžadujúce vždy elektrickú rúru.|Mrazené jedlá ako jedinú zásobu pre výpadok prúdu.|Zásoby majú byť bezpečné, použiteľné a pravidelne kontrolované.
Rodina má dohodnuté stretnutie pri moste. Úrady však most uzavrú. Čo platí?|Rodinný plán treba prispôsobiť aktuálnym pokynom.|Dohodnuté miesto má prednosť, inak sa rodina nenájde.|Most sa smie použiť, ak ide iba o krátke stretnutie.|Rodinná dohoda pomáha pri rozdelení, ale nesmie viesť do zakázaného alebo nebezpečného priestoru.
@5|aid
Pri podozrení na zlomeninu predlaktia…|podopriem ju v šetrnej polohe a privolám pomoc.|najprv ju narovnám, aby sa lepšie zmestila do závesu.|najprv porovnám rozsah pohybu s neporanenou rukou.|Končatinu zbytočne nepohybujeme a nenaprávame.
Kedy možno použiť zotavovaciu polohu na boku?|Pri bezvedomí s normálnym dýchaním, bez podozrenia na úraz.|Pri bezvedomí s občasným lapavým dychom, bez viditeľnej rany.|Pri bezvedomí bez dýchania, kým sa čaká na záchrannú službu.|Privolaj 155, udržuj priechodné dýchacie cesty a sleduj dýchanie; pri úraze postupuj podľa operátora.
Človek nereaguje na oslovenie. Čo je potrebné?|Volám 155 a podľa operátora posúdim dýchanie.|Najprv niekoľko minút čakám, či sa preberie.|Najprv ho posadím, aby sa mu lepšie dýchalo.|Bezvedomie je vážny stav; človeku nič nedávaj do úst.
Prečo zraneného po páde z výšky zbytočne nepremiestňujeme?|Zbytočný presun môže zhoršiť poranenie chrbtice.|Poranenie chrbtice sa dá vylúčiť, keď vie pohnúť rukou.|Presun je potrebný vždy, keď si človek pamätá pád.|Voláme pomoc; pohyb môže byť nutný pri bezprostrednom ohrození alebo na zaistenie dýchania.
Poranenú ruku treba podoprieť. Ktorá pomôcka je na záves najvhodnejšia?|Trojrohá šatka.|Náplasť s vankúšikom.|Sterilný štvorček.|Trojrohá šatka môže podoprieť ruku. Krytie a náplasť slúžia najmä na rany, nie na podopretie celej končatiny.
Pri zranení členka na túre je vhodné…|nohu prestať zaťažovať a oznámiť úraz dospelému.|pokračovať pomaly, ak sa členok vojde do topánky.|najprv skúsiť niekoľko krokov na špičke poranenej nohy.|Zranenie treba posúdiť; nútený pohyb ho môže zhoršiť.
Čo zistíš skôr, než sa priblížiš k zranenému?|Či nehrozí nebezpečenstvo aj pomocníkovi.|Či má zranený pri sebe preukaz poistenca.|Či pozná niekto presnú príčinu jeho pádu.|Pomocník sa nemá stať ďalším zraneným.
V rane je zapichnutý väčší predmet. Čo s ním?|Nechám ho na mieste a privolám pomoc.|Vytiahnem ho až po pripravení obväzu.|Uvoľním ho kývaním, potom prekryjem ranu.|Vybratie predmetu môže zhoršiť krvácanie; tlak smeruje okolo neho.
Čo povieš vystrašenému zranenému?|Pomoc je privolaná, zostanem pri tebe.|Určite je to len drobnosť, vyšetrenie nebude treba.|Keď prestaneš plakať, bolesť už bude preč.|Hovor pokojne a pravdivo, bez nereálnych sľubov.
Kedy ukončíš tiesňový hovor?|Na pokyn operátora po dohodnutí ďalšieho postupu.|Hneď po potvrdení, že pozná adresu udalosti.|Hneď ako operátor povie, že pomoc vysiela.|Operátor môže potrebovať ďalšie údaje a dávať dôležité pokyny.
@5|orientation
Na kovovej lavičke ukazuje kompas inak než o pár krokov ďalej. Čo urobíš?|Zopakujem meranie vodorovne mimo kovu.|Za správny vezmem údaj z pevnej lavičky.|Vypočítam priemer oboch smerov bez ďalšej kontroly.|Kov môže strelku vychýliť. Priemer chybného a správneho údaja nie je spoľahlivá oprava.
Čo je orientovanie mapy?|Natočenie mapy tak, aby jej smery súhlasili s terénom.|Natočenie mapy vždy horným okrajom v smere našej chôdze.|Natočenie mapy tak, aby sa všetky názvy čítali vodorovne.|Orientovaná mapa má smery zhodné s terénom.
[map] Zo školy sa pozrieš na rieku na juhu. Na ktorej strane máš les?|Naľavo, na východe.|Napravo, na západe.|Za sebou, na severe.|Pri pohľade na juh je východ naľavo. Strany tela sa pri otočení zmenia, svetové strany zostávajú.
Je mach na strome spoľahlivý ukazovateľ severu?|Nie, jeho rast závisí aj od vlhkosti a zatienenia.|Áno, ak je na kmeni väčšia súvislá plocha machu.|Áno, keď je kmeň dostatočne starý a hrubý.|Prírodné znaky sú neisté; kombinuj mapu, kompas a viac bodov.
Na mape sú dva podobné mosty. Ako overíš, pri ktorom stojíš?|Porovnám aj rázcestie a smer rieky v okolí.|Vyberiem most bližšie k stredu mapy.|Vyberiem most, ku ktorému vedie hrubšia čiara.|Jeden podobný bod môže zavádzať. Poloha sa overuje pomocou viacerých zhodných prvkov.
Na odmeranom úseku urobíš približne 100 krokov na 70 m. Aká je vzdialenosť 200 podobných krokov?|Približne 140 m.|Približne 200 m.|Približne 280 m.|Dvojnásobný počet rovnako dlhých krokov dá dvojnásobnú vzdialenosť. V teréne ide stále o odhad.
Ktorý bod je vhodný na overenie polohy?|Rázcestie, ktorého vetvy a značenie súhlasia s mapou.|Skupina stromov, ktorá sa podobá obrázku v legende.|Najširšia cesta v dohľade bez kontroly jej smeru.|Výrazné body zakreslené v mape pomáhajú určiť polohu.
Smerovník uvádza čas 1 h. Čo znamená?|Orientačný čas, ktorý ovplyvní tempo a podmienky.|Čas pre celú skupinu už vrátane všetkých prestávok.|Čas, ktorý platí rovnako pri výstupe aj na klzkom zostupe.|Tempo skupiny, prestávky a terén môžu čas predĺžiť.
Čo patrí k príprave pochodu?|Skontrolovať trasu, predpoveď, výbavu a možnosti návratu.|Skontrolovať dĺžku trasy, ostatné vyriešiť až na mieste.|Vybrať trasu podľa najrýchlejšieho člena a vyraziť neskôr.|Príprava pomáha predchádzať problémom počas túry.
Na mieste je staré ohnisko, ale platí zákaz zakladania ohňa. Čo urobí skupina?|Oheň nezaloží ani v existujúcom ohnisku.|Založí malý oheň, ak pri ňom bude vedro vody.|Použije ohnisko, pretože jeho existencia znamená povolenie.|Staré ohnisko nie je dôkaz aktuálneho povolenia. Rozhodujú miestne pravidlá a platné zákazy.
@5|nature
Čo je biodiverzita?|Rozmanitosť druhov, ich vlastností a prostredí.|Celkový počet jedincov jedného druhu v území.|Celková rozloha lesa bez ohľadu na jeho zloženie.|Zahŕňa pestrosť druhov, ich genetických vlastností a ekosystémov.
Prečo nekrmíme voľne žijúce zvieratá desiatou?|Môžeme im uškodiť a zvykať ich na ľudí.|Škodí iba kŕmenie soleným jedlom, ostatné je vhodné.|Ak ide o ovocie, mení sa iba jedálniček, nie správanie.|Ľudské jedlo často nie je vhodné a mení prirodzené správanie.
Čo je šetrnejšie na výlete v rezervácii?|Zostať na povolenej trase a všetko po sebe odniesť.|Opustiť trasu, ak pritom nezostane žiadny odpad.|Prejsť cez uzáveru potichu v malej skupine.|Rešpektovanie trasy chráni prostredie aj jeho obyvateľov.
Na chodníku sú črepy a nemáš pomôcky na zber. Čo je najvhodnejšie?|Upozorniť ostatných a oznámiť miesto dospelému.|Zabaliť črepy do tenkej vreckovky a vložiť ich do vrecka.|Odkopnúť črepy do trávy, kde po nich ľudia nešliapu.|Črepy môžu porezať aj v tráve alebo cez tenký papier. Zber má byť bezpečný, s vhodnými pomôckami.
Aký význam majú mokrade?|Zadržiavajú vodu a poskytujú biotopy mnohým druhom.|Pomáhajú iba vtedy, keď majú stále rovnakú hladinu.|Zadržiavajú vodu, preto je vhodné všetky prehĺbiť na bazény.|Mokrade sú dôležitou súčasťou kolobehu vody a života.
Ktorý príklad predchádza vzniku odpadu ešte pred triedením?|Použitie vlastnej fľaše namiesto nákupu novej.|Roztriedenie nových fliaš po každom nákupe.|Zlisovanie nových obalov pred ich odovzdaním do zberu.|Predchádzanie odpadu znamená znížiť jeho vznik. Triedenie a lisovanie riešia odpad, ktorý už vznikol.
Prečo môžu skratky na strmom svahu škodiť?|Odhaľujú pôdu, ktorú potom ľahšie odnáša voda.|Skrátením chodníka sa znižuje erózia bez ohľadu na svah.|Ušliapaná pôda vždy vsakuje viac dažďovej vody.|Poškodená pôda je náchylnejšia na eróziu.
Čo urobíš pri náleze čiernej skládky?|Z bezpečia s dospelým nahlásim miesto obci.|Najprv otvorím vrecia, aby bolo hlásenie presnejšie.|Presuniem neznáme nádoby ku ceste na ľahší odvoz.|Na skládke môžu byť nebezpečné látky a ostré predmety.
Ktorá vec je vhodná na opakované používanie na túre?|Opakovane používaná pevná nádoba na jedlo.|Nový ľahký obal s označením recyklovateľnosti.|Nový papierový obal pri každej prestávke.|Trvácna výbava pomáha znížiť množstvo obalov.
Pred výletom poznáš trasu z minulého roka. Čo ešte overíš v návštevnom poriadku?|Aktuálne obmedzenia a prípadné sezónne uzávery.|Len dĺžku trasy, pravidlá sa po jej vytýčení nemenia.|Len farbu značky, tá povoľuje vstup počas celého roka.|Znalosť trasy ani turistická značka nenahrádzajú kontrolu aktuálnych pravidiel a uzáver.
@6|civil
Na čistiacom prípravku je symbol žieraviny. Čo hrozí?|Poškodenie kože a očí pri kontakte.|Predovšetkým ľahké zapálenie pri izbovej teplote.|Predovšetkým nebezpečný tlak plynu v obale.|Žieraviny môžu spôsobiť vážne poranenia; s prípravkom nemanipuluj bez dozoru.
Prečo sa nemiešajú rôzne čistiace prostriedky?|Môžu reagovať a uvoľňovať nebezpečné plyny.|Riziko vzniká iba pri miešaní výrobkov rôznych značiek.|Riedenie vodou vopred vylúči riziko každej kombinácie.|Napríklad niektoré kombinácie s chlórovým prípravkom sú nebezpečné.
Čo urobíš pri požiari elektrického spotrebiča?|Ustúpim, upozorním ostatných a privolám pomoc.|Najprv sa priblížim a skúsim odpojiť horiaci kábel rukou.|Najprv nalejem malé množstvo vody iba na plameň.|Voda a elektrina sú nebezpečná kombinácia; žiak nemá riskovať hasenie.
Niekto chce hasiť horiaci olej vodou. Prečo je to nebezpečné?|Voda môže prudko rozprsknúť horiaci olej.|Voda predĺži horenie len tým, že olej ochladí.|Riziko vzniká len vtedy, ak je voda teplá.|Voda môže pri styku s horúcim olejom prudko prejsť na paru a rozšíriť horenie. Žiak ustúpi a upozorní dospelého.
Čo znamená dekontaminácia?|Odstránenie alebo zníženie nebezpečného znečistenia.|Premiestnenie obyvateľov mimo ohrozeného priestoru.|Vyhlásenie varovného signálu pre ohrozené územie.|Postup závisí od druhu látky a pokynov odborníkov.
Úrady nariadia ukrytie pri chemickej havárii. Čo s vetraním?|Obmedzíme prívod vonkajšieho vzduchu podľa pokynov.|Necháme malé okno otvorené na strane odvrátenej od úniku.|Zapneme silnejšie vetranie, aby sa prípadný plyn zriedil.|Tým obmedzíme prenikanie vonkajších škodlivín.
Operátor sa pri požiari pýta, či je niekto v budove. Nie si si istý. Čo povieš?|Poviem, čo viem, a jasne uvediem neistotu.|Poviem, že je prázdna, aby sa hovor zbytočne nepredĺžil.|Vojdem dnu a odpoviem až po vlastnej kontrole.|Neistotu nezakrývaj odhadom. Operátorovi odovzdaj pozorovania bez riskantného zisťovania ďalších údajov.
Pri úniku plynu z bytu sa pomoc volá…|z bezpečného miesta mimo podozrivého priestoru.|z kuchyne pri otvorenom okne počas kontroly úniku.|z vedľajšej miestnosti po zapnutí elektrického vetrania.|Pri podozrení na plyn nepoužívaj v ohrozenom priestore zdroje iskier.
Trieda nacvičuje tiesňový hovor. Ako to urobí bez zbytočného volania na 112?|Úlohu operátora prevezme učiteľ v modelovej situácii.|Zavolá na 112 a hneď na začiatku povie, že ide o cvičenie.|Zavolá krátko bez hovoru, aby overila dostupnosť linky.|Nácvik sa dá robiť modelovo. Verejná tiesňová linka je určená skutočným udalostiam.
Zablokovaný únikový východ si všimneš ešte pred poplachom. Čo urobíš?|Ohlásim prekážku hneď pracovníkovi školy.|Odložím hlásenie na najbližší cvičný poplach.|Spolieham sa, že druhý východ tento problém vyrieši.|Prevencia zahŕňa aj priechodné únikové cesty.
@6|aid
Ako rozlíšiš vykĺbenie od zlomeniny bez vyšetrenia?|Nemusím určiť diagnózu; nenaprávam a zabezpečím pomoc.|Ak sa prsty hýbu, môžem zlomeninu vylúčiť.|Ak koža nie je porušená, ide iba o vyvrtnutie.|Prvá pomoc nevyžaduje presnú diagnózu ani násilné testovanie.
Čo sleduješ po priložení obväzu na ruku?|Prekrvenie a citlivosť prstov pod obväzom.|Rovnakú šírku všetkých otočení bez kontroly prstov.|Tesnosť podľa toho, či sa pod obväz zmestí pero.|Blednutie, chlad a tŕpnutie môžu upozorniť na príliš tesný obväz.
Sterilné krytie spadne otvorenou stranou na lavičku. Máš nové balenie. Čo spravíš?|Použijem nové krytie a chránim jeho kontaktnú stranu.|Použijem pôvodné, ak na ňom nevidno nečistotu.|Pôvodné otočím a utriem ho zvonka rukavicou.|Sterilita sa nedá posúdiť pohľadom. Kontaktná strana po dotyku s lavičkou už nie je spoľahlivo čistá.
Pri krvácaní z nosa je vhodné…|sadnúť si v predklone a stlačiť mäkkú časť nosa.|sadnúť si v záklone a stlačiť mäkkú časť nosa.|sadnúť si v predklone a stláčať najmä koreň nosa.|Mäkkú časť nosa držíme súvisle 10 až 15 minút; pri silnom či pretrvávajúcom krvácaní vyhľadáme pomoc.
Ako pristupuješ k podozreniu na zlomeninu nohy?|Nohu nezaťažujem, podopriem a privolám pomoc.|Skúsim, či unesie váhu, a podľa toho rozhodnem.|Vyrovnám jej polohu podľa zdravej nohy a potom zavolám.|Násilný pohyb môže zhoršiť poškodenie.
Na čo slúži chladný obklad cez tkaninu pri ľahšom vyvrtnutí?|Môže dočasne zmierniť bolesť a opuch.|Pokles bolesti po obklade spoľahlivo vylúči zlomeninu.|Po chladení je možné ihneď pokračovať v plnej záťaži.|Chladenie nenahrádza posúdenie úrazu a ľad neprikladáme priamo na kožu.
Prečo sa nedotýkame krvi holými rukami, ak máme ochranné pomôcky?|Obmedzujeme kontakt s potenciálne infekčným materiálom.|Rukavice odstránia potrebu hygieny rúk po ošetrení.|Rukavice zachovajú čistotu krytia aj po dotyku zeme.|Použi dostupnú bariéru, ale neodkladaj privolanie pomoci.
Pri ktorej rane treba najnaliehavejšie volať 155?|Krv rýchlo presakuje a zranený slabne.|Malá odrenina už nekrváca a človek je v poriadku.|Staršia ranka po výmene náplasti krátko zaštípala.|Rýchla strata krvi a slabnutie sú varovné prejavy. Prítlak na ranu a tiesňové volanie sa neodkladajú.
Kam umiestniš uzol podporného závesu poranenej ruky?|Mimo rany a citlivého miesta, aby záves netlačil.|Nad miestom najväčšej bolesti, aby ho uzol spevnil.|Na zadnej strane krku čo najtesnejšie, aby sa neposúval.|Záves má podopierať ruku bez ďalšej bolesti či obmedzenia dýchania.
Zranenému začne byť počas čakania na pomoc horšie. Čo spravíš?|Znovu posúdim stav a zmenu oznámim operátorovi.|Vyčkám na príjazd, keďže hovor už bol ukončený.|Najprv ho postavím, aby som overil mieru slabosti.|Stav sa môže meniť a operátor upraví pokyny.
@6|orientation
Na mape 1 : 25 000 meria úsek 3 cm. Akú vzdialenosť predstavuje?|750 m.|75 m.|1 250 m.|Jeden centimeter predstavuje 250 m. Tri centimetre sú 3 × 250 = 750 m.
Na mape 1 : 50 000 meria cesta 4 cm a obchádzka pridá 1 cm. Koľko je to spolu?|2,5 km.|2 km.|5 km.|Spolu ide o 5 cm. Pri tejto mierke je 1 cm 500 m, teda 5 cm je 2,5 km.
Čo je azimut?|Uhol od severu meraný v smere hodinových ručičiek.|Uhol od severu meraný proti smeru hodinových ručičiek.|Uhol od východu meraný v smere hodinových ručičiek.|Azimut opisuje smer pomocou uhla.
Pri pochode zmeníš azimut z 0° na 90°. Aké otočenie urobíš?|O štvrť otáčky doprava.|O štvrť otáčky doľava.|O pol otáčky doprava.|Azimut sa meria od severu v smere hodinových ručičiek. 90° je východ, teda štvrť otáčky doprava od severu.
Kráčaš azimutom 180° a chceš sa vrátiť priamo späť. Aký azimut zvolíš?|0° alebo 360°.|90°.|270°.|Opačný smer sa líši o 180°. Oproti juhu leží sever.
[map] Zo školy ideš k lesu a potom sa vraciaš priamo ku škole. Aký azimut má návrat?|270°.|90°.|180°.|Cesta k lesu smeruje na východ (90°). Návrat je na západ, teda 270°.
Na tej istej mape majú dva svahy rovnaký výškový rozdiel. Kde je svah strmší?|Tam, kde sú vrstevnice bližšie pri sebe.|Tam, kde sú vrstevnice ďalej od seba.|Oba musia byť rovnako strmé pri rovnakom rozdiele výšok.|Strmosť závisí aj od vodorovnej vzdialenosti. Rovnaké stúpanie na kratšom úseku znamená strmší svah.
Prečo meriame trasu po jej zákrutách?|Priama spojnica môže skutočnú dĺžku podhodnotiť.|Zákruty menia mierku mapy oproti rovnému úseku.|Meranie vzdušnou čiarou vždy pridáva vzdialenosť navyše.|Dĺžku túry určuje priebeh cesty, nie iba spojnica cieľov.
Na hrebeni sa blíži búrka. Čo je správne?|Hrebeň opustím včas bezpečnou ústupovou trasou.|Pokračujem po hrebeni, pokiaľ ešte neprší.|Počkám pod osamelým stromom, kým bude búrka bližšie.|Prevencia a včasný ústup sú účinnejšie než riešenie búrky na hrebeni.
Kedy je sever určený kompasom menej spoľahlivý?|Kovové zábradlie môže vychýliť strelku.|Zamračená obloha mení magnetický sever.|Otočenie papierovej mapy mení smer strelky v teréne.|Magnetické rušenie môže spôsobiť nesprávny smer.
@6|nature
Po daždi je pod novou skratkou na svahu nános zeminy. Čo sa pravdepodobne stalo?|Voda odniesla obnaženú pôdu zo svahu.|Pôda sa na skratke zhutnila bez presunu materiálu.|Voda sa vsiakla na mieste bez pohybu pôdy.|Skratka narušila porast. Voda z nej ľahšie odnáša pôdu, čo je erózia.
Aký problém môže spôsobiť vypúšťanie oleja do odtoku?|Zaťažuje kanalizáciu a sťažuje čistenie vody.|Ak ho zriedime horúcou vodou, vplyv sa odstráni.|Ak ide o rastlinný olej, rozloží sa ešte v potrubí.|Použitý kuchynský olej odovzdávame podľa miestnych možností zberu.
Kam patria použité batérie?|Do určeného oddeleného zberu batérií.|Do zberu kovových obalov spolu s plechovkami.|Do zmesového odpadu, keď už sú úplne vybité.|Oddelený zber umožňuje bezpečnejšie spracovanie batérií.
Čo znamená invázny nepôvodný druh?|Zavlečený druh, ktorý sa šíri a môže poškodzovať prostredie.|Každý nepôvodný druh bez ohľadu na jeho šírenie a vplyv.|Každý pôvodný druh, ktorý sa vyskytuje vo veľkom počte.|Nie každý nepôvodný druh je invázny; podstatné sú šírenie a negatívne dôsledky.
Prečo je staré mŕtve drevo v lese užitočné?|Je prostredím organizmov a postupne vracia živiny.|Má význam iba dovtedy, kým je na ňom zelené lístie.|Každý odumretý kmeň znižuje pestrosť okolitého lesa.|Rozklad dreva je prirodzenou súčasťou lesného ekosystému.
Ako naložíš s nájdenou neznámou chemikáliou pri potoku?|Nemanipulujem s nálezom a oznámim miesto.|Najprv ju premiestnim od vody, nech neohrozí potok.|Najprv nádobu otvorím, aby som zistil jej obsah.|Neodborná manipulácia môže rozšíriť znečistenie.
Prečo je užitočný pestrý pás kvetov pri škole?|Rôzne kvety poskytujú potravu v rôznom čase.|Opeľovačom najviac vyhovuje porast bez kvitnutia.|Zmysel má iba pás, kde všetky druhy kvitnú naraz.|Rôzne rastliny poskytujú potravu v rozličných častiach sezóny.
Čo je správne pri triedení znečisteného obalu?|Overiť miestne pravidlá pre materiál aj znečistenie.|Triediť podľa vonkajšieho materiálu bez ohľadu na zvyšky.|Všetky kombinované obaly automaticky vhodiť do papiera.|Silne znečistený materiál môže znehodnotiť triedený zber.
Prečo v chránenom území nepúšťame psa voľne tam, kde to pravidlá zakazujú?|Aj pokojný pes môže rušiť živočíchy alebo ich naháňať.|Výnimku má každý pes, ktorý reaguje na svoje meno.|Pravidlo sa týka iba psov, ktoré už niekoho pohrýzli.|Aj pokojný pes môže ovplyvniť voľne žijúce zvieratá.
Ktoré opatrenie šetrí materiál najskôr, ešte pred recykláciou?|Oprava veci a predĺženie jej používania.|Výmena funkčnej veci za novú s recyklovateľným obalom.|Vytvorenie zásoby náhradných vecí bez reálnej potreby.|Predĺženie životnosti môže predísť výrobe ďalšej veci a vzniku odpadu.
@7|civil
Aký je rozdiel medzi dezinfekciou a dezinsekciou?|Dezinfekcia pôsobí proti pôvodcom nákaz, dezinsekcia proti škodlivému hmyzu.|Dezinfekcia pôsobí proti hmyzu, dezinsekcia proti pôvodcom nákaz.|Dezinfekcia pôsobí proti hlodavcom, dezinsekcia proti rádioaktívnym látkam.|Podobné názvy označujú odlišné postupy ochrany zdravia.
Po zaplavení skladu treba riešiť výskyt potkanov. Ktorý odborný zásah tomu zodpovedá?|Deratizácia.|Dezinsekcia.|Dezaktivácia.|Deratizácia sa týka škodlivých hlodavcov. Dezinsekcia hmyzu a dezaktivácia rádioaktívnej kontaminácie.
Ako chránime núdzové zásoby vody pri znečistení okolia?|V neporušených uzavretých obaloch podľa pokynov.|Preliatím do otvorenej nádoby v čistej miestnosti.|Prefiltrovaním cez látku a uložením v otvorenej nádobe.|Uzavretý obal znižuje riziko kontaminácie z okolia.
Prečo sa v úkryte dodržiavajú pokyny vedúceho?|Spoločný režim umožňuje bezpečne využívať priestor a zásoby.|Každý najlepšie posúdi, kedy sám otvorí prívod vonkajšieho vzduchu.|Pravidlá sú potrebné iba v úkryte, ktorý nemá elektrické osvetlenie.|Organizácia pomáha chrániť všetkých prítomných.
Z motorového priestoru auta stúpa dym. Ako sa zachová žiak?|Vzdiali sa do bezpečia a upozorní na udalosť.|Otvorí kapotu, aby sa nahromadený dym uvoľnil.|Vyberie batožinu, kým ešte nevidí otvorený plameň.|Požiar vozidla môže rýchlo postupovať; dôležitý je bezpečný odstup.
Čo patrí k ochrane potravín po chemickej havárii?|Riadime sa pokynmi a podozrivo zasiahnuté jedlo nepoužijeme.|Zasiahnuté potraviny použijeme, ak nemajú zmenenú vôňu.|Zasiahnuté jedlo vždy stačí dlhšie povariť pred konzumáciou.|Nebezpečné znečistenie nemusí zmeniť chuť ani vôňu.
Ako správne skladovať ochranný prostriedok, ak je pridelený?|Podľa návodu, s kontrolou stavu a dostupnosti.|Na priamom slnku, aby sa priebežne vysušoval.|V neoznačenom spoločnom obale bez rozlíšenia veľkostí.|Poškodený alebo nevhodný prostriedok nemusí poskytovať očakávanú ochranu.
Môžeš znečistenú vodu po chemickej havárii považovať po prevarení za bezpečnú?|Nie, prevarenie neodstráni všetky chemické látky.|Áno, keď po prevarení zostane bez farby a zápachu.|Áno, ak sa pred varením precedí cez hustú tkaninu.|Pri chemickom znečistení používaj odporúčaný bezpečný zdroj vody.
Ktorá správa má pri mimoriadnej udalosti väčšiu váhu?|Aktuálny pokyn príslušného úradu pre danú lokalitu.|Najviac zdieľané upozornenie bez uvedeného času.|Starší pokyn pre susednú obec s podobným problémom.|Overenie zdroja, dátumu a miesta bráni šíreniu nepravdivých informácií.
Čo spravíš, ak potrebuje spolužiak pri evakuácii pomoc s pohybom?|Upozorním učiteľa a pomôžem podľa evakuačného plánu.|Pošlem ostatných ďalej a bez oznámenia zostanem bokom.|Presvedčím ho, nech skúsi schody bez svojej pomôcky.|Pomoc má rešpektovať jeho potreby a evakuačný plán.
@7|aid
Dospelý nereaguje a iba občas lapá po dychu. Čo to znamená?|Je to abnormálne dýchanie; volám 155 a začínam KPR.|Každý občasný nádych vylučuje potrebu stláčania hrudníka.|Ide o normálne dýchanie; postačí poloha na boku a čakanie.|Lapavé dychy môžu byť prejavom zastavenia obehu.
Pri nácviku KPR dospelého žiak robí asi 70 stlačení za minútu. Ako upraví tempo?|Zrýchli približne na 100 až 120 za minútu.|Ponechá tempo, ak sú stlačenia dostatočne hlboké.|Zrýchli približne na 150 až 170 za minútu.|Odporúčané tempo u dospelého je 100 až 120 stlačení za minútu; potrebná je aj správna hĺbka a uvoľnenie hrudníka.
Aká je hĺbka stlačení hrudníka dospelého?|5 až 6 cm.|3 až 4 cm.|7 až 8 cm.|Hrudník dospelého stláčame 5 až 6 cm a po stlačení ho necháme uvoľniť.
Vyškolený záchranca vykonáva KPR dospelého aj s vdychmi. Aký pomer použije?|30 stlačení a 2 vdychy.|15 stlačení a 2 vdychy.|30 stlačení a 5 vdychov.|Pri štandardnej KPR dospelého s vdychmi je pomer 30 : 2; operátor môže viesť postup.
Čo urobíš pri silnom krvácaní z rany bez cudzieho predmetu?|Udržujem pevný tlak a zabezpečím volanie 155.|Najprv vymývam ranu, až potom začnem s tlakom.|Tlačím prerušovane, aby som pravidelne videl krvácanie.|Priamy tlak a rýchle privolanie pomoci sú základné kroky.
Pri otvorenej zlomenine vidno kosť. Ktorý postup je správny?|Chránim ranu, kosť nenaprávam a privolám pomoc.|Kosť najprv jemne zasuniem, potom ranu prekryjem.|Končatinu najprv narovnám podľa druhej, potom zavolám.|Kosť sa nezatláča do rany ani nenapráva. Manipuláciu obmedzujeme a zabezpečíme odbornú pomoc.
Zranený je bledý, spotený a slabne. Ako pomôžeš?|Privolám pomoc, chránim pred chladom a sledujem dýchanie.|Nechám ho prechádzať sa, aby sa mu zlepšil krvný obeh.|Najprv mu dám veľké jedlo a čakám na návrat síl.|Môže ísť o obehové zlyhávanie; potrebná je rýchla odborná pomoc.
V miestnosti s podozrením na únik plynu leží človek. Čo urobíš?|Nevstupujem do priestoru a volám 112 z bezpečia.|Vstúpim s mokrou látkou na tvári a skúsim ho vytiahnuť.|Vstúpim so zadržaným dychom, ak leží blízko dverí.|Nechránený záchranca sa môže tiež otráviť; zásah patrí vybaveným zložkám.
Niekto požil neznámu chemikáliu. Čo je vhodné?|Volám 155, uvediem dostupné údaje o látke a nevyvolávam vracanie.|Najprv vyvolám vracanie, aby sa látka dostala čo najskôr von.|Najprv podám mlieko na zriedenie, až potom zistím, čo vypil.|Postup závisí od látky; riaď sa odbornými pokynmi.
Po úraze má človek silnú bolesť krku. Čo je najvhodnejšie?|Zbytočne s ním nehýbem a privolám 155.|Posadím ho, aby sa znížil tlak hlavy na krk.|Overím otáčanie hlavy, aby som vylúčil vážne poranenie.|Možné poranenie chrbtice vyžaduje opatrnosť; dýchanie má pritom prednosť.
@7|orientation
Trasa má 9 km pri tempe 3 km/h. Skupina chce tri prestávky po 10 minút. Aký je plánovaný čas?|3 hodiny 30 minút.|3 hodiny 10 minút.|3 hodiny 50 minút.|Čistá chôdza trvá 9 ÷ 3 = 3 hodiny. Tri desaťminútové prestávky pridajú pol hodiny; ďalšiu rezervu môže vyžadovať terén.
Prečo do harmonogramu túry pridávame rezervu?|Aby plán počítal aj so zdržaním a pomalším postupom.|Aby sa počas posledného úseku dalo tempo vždy zdvojnásobiť.|Aby sa pri neskorom štarte mohli vynechať kontroly trasy.|Plán nemá rátať iba s ideálnou rýchlosťou.
Kde je rozumnejšie postaviť stan, ak je tam táborenie povolené?|Na povolenom mieste mimo koryta a poškodených stromov.|Na rovnej ploche v suchom koryte, keď tam práve netečie voda.|Tesne pri brehu na nízkej ploche, aby bola voda vždy poruke.|Aj suché koryto môže pri daždi rýchlo zaplaviť voda.
Pred skupinou je rozvodnený potok bez bezpečného mosta. Čo urobíte?|Hľadáme bezpečnú obchádzku alebo sa vrátime.|Prebrodíme ho v skupine, ak voda nedosahuje kolená.|Prejdeme po jednom, keď každý vie dobre plávať.|Rýchlosť a silu vody možno ľahko podceniť.
Čo si overíte pred použitím lávky?|Aktuálny stav a prípadné obmedzenie vstupu.|Iba zakreslenie lávky v našej minuloročnej mape.|Iba to, či po nej pred chvíľou niekto prešiel.|Poškodená alebo uzavretá lávka nie je bezpečná skratka.
Pri prudkom daždi v úzkej doline…|včas odídeme z priestoru ohrozeného prívalovou vodou.|počkáme pod mostom, ktorý nás ochráni pred dažďom.|zostaneme v suchom koryte, kým voda nezačne stúpať pri nás.|V úzkych dolinách môže voda vystúpiť veľmi rýchlo.
[map] Z lesa ideš ku škole, potom k stanu. Ktorú postupnosť azimutov použiješ?|270° a potom 0°.|90° a potom 0°.|270° a potom 180°.|Z lesa ku škole je smer západ (270°). Od školy k stanu pokračuješ na sever (0° alebo 360°).
Kto má vedieť o plánovanej trase skupiny?|Zodpovedná osoba poznajúca trasu aj čas návratu.|Kamarát, ktorý vie iba názov cieľového vrcholu.|Náhodný turista, ktorému pri štarte povieme smer cesty.|Informácia o trase uľahčí pomoc pri omeškaní alebo probléme.
Čo spravíš, keď sa zhorší počasie oproti predpovedi?|Plán upravím podľa aktuálneho vývoja a možností skupiny.|Ponechám plán, ak bola ranná predpoveď priaznivá.|O ústupe rozhodnem až po minutí zásob vody.|Aktuálne podmienky majú prednosť pred pôvodným cieľom.
Offline mapa je stiahnutá, ale telefón má skoro vybitú batériu. Čo je pravda?|Mapa nepotrebuje dáta, na zobrazenie však potrebuje energiu.|Stiahnutá mapa zobrazuje polohu aj na vypnutom telefóne.|Bez dát offline mapa vždy prestane zobrazovať aj samotný terén.|Offline znamená bez dátového pripojenia, nie bez napájania. Orientácia potrebuje zálohu pre prípad poruchy zariadenia.
@7|nature
Čo je ekologická stopa v bežnom chápaní?|Nároky nášho spôsobu života na prírodné zdroje.|Množstvo vytriedeného odpadu bez ohľadu na spotrebu.|Počet kilometrov prejdených pešo bez ohľadu na ostatné činnosti.|Spotreba, doprava aj odpad súvisia s využívaním zdrojov.
Prečo zvyšky jedla pri stanovaní bezpečne ukladáme?|Aby sme nelákali zvieratá potravou do tábora.|Aby sa vôňa jedla sústredila práve pri stanoch.|Aby sa zvyšky dali ráno ponechať na jednom mieste.|Potrava pri tábore môže viesť k nebezpečným stretnutiam so zvieratami.
Na obale saponátu je napísané „biologicky rozložiteľný“. Môže sa riad umývať priamo v potoku?|Nie, aj tak použijeme určené miesto a spôsob likvidácie vody.|Áno, rozložiteľnosť povoľuje priame vypúšťanie do toku.|Áno, ak za nami už na danom mieste nikto netáborí.|Rozložiteľnosť neznamená okamžitú neškodnosť. Čistiace látky sa nevypúšťajú priamo do prírodných vôd.
Čo môže spôsobiť nadbytok živín vo vode?|Premnoženie rias a neskorší pokles kyslíka.|Trvalé zvýšenie kyslíka bez možnosti jeho nedostatku.|Zvýšenie pitnosti vody vďaka hustejšiemu porastu rias.|Nadbytok živín môže narušiť rovnováhu vodného ekosystému.
Ako správne hodnotiť označenie výrobku „ekologický“?|Overiť konkrétne údaje a dôveryhodnosť tvrdenia.|Považovať zelený obal za dôkaz nízkej záťaže.|Posúdiť šetrnosť hlavne podľa slova „prírodný“ v názve.|Farba a reklamné tvrdenie samy nepotvrdzujú šetrnosť výrobku.
Čo znamená sezónna uzávera chodníka?|Dočasný zákaz alebo obmedzenie podľa stanovených pravidiel.|Obmedzenie platné len pre veľké organizované skupiny.|Odporúčanie, z ktorého sú skúsení turisti vyňatí.|Uzávera môže súvisieť s ochranou prírody alebo bezpečnosťou.
Prečo sa pri obnove poškodeného brehu radíme s odborníkmi?|Zásah musí vyhovovať miestnemu prostrediu a nezhoršiť stav.|Každé spevnenie brehu betónom automaticky pomôže prírode.|Každá rýchlorastúca vysadená rastlina je vhodná na obnovu.|Obnova prostredia musí zodpovedať miestnym podmienkam.
Aký význam majú biokoridory?|Prepájajú biotopy a umožňujú presun organizmov.|Oddeľujú populácie, aby sa medzi nimi obmedzil pohyb.|Slúžia najmä na rýchlejší prechod turistov medzi obcami.|Prepojenie pomáha populáciám, ktoré by inak boli izolované.
Čo urobíš pri náleze mláďaťa srny bez viditeľného zranenia?|Nechám ho na mieste a vzdialim sa.|Počkám tesne pri ňom, kým sa objaví jeho matka.|Prenesiem ho pod hustejší krík a označím miesto.|Matka sa môže zdržiavať nablízku; samotné mláďa nemusí byť opustené.
Ktorý postup najlepšie znižuje odpad pri školskom podujatí?|Plánovanie porcií a použitie opakovane využiteľného riadu.|Nákup väčšej zásoby jednorazového riadu s nápisom „eko“.|Rozdanie samostatného nového obalu na každý chod jedla.|Predchádzanie odpadu začína už pri plánovaní podujatia.
@8|civil
Pri radiačnej udalosti niekto tvrdí, že jódová tableta chráni celé telo pred žiarením. Čo je správne?|Má konkrétny účel pre štítnu žľazu a užíva sa na pokyn úradov.|Po užití nahrádza ochranu dýchacích ciest aj pobyt v úkryte.|Pri vyššej dávke poskytuje ochranu aj pred vonkajším ožiarením.|Jódová profylaxia obmedzuje prijatie rádioaktívneho jódu štítnou žľazou. Nechráni pred všetkými druhmi žiarenia a nenahrádza ďalšie opatrenia.
Pri pokyne na ukrytie po radiačnej udalosti…|vojdem do vhodnej budovy a sledujem ďalšie pokyny.|odídem pešo čo najďalej, aj keď je nariadené ukrytie.|otvorím okná, aby sa prípadná kontaminácia rozptýlila.|Budova a obmedzenie pobytu vonku môžu znížiť expozíciu; postup určuje situácia.
Na odeve sa zachytil rádioaktívny prach. Ako nazveme tento stav?|Rádioaktívna kontaminácia odevu.|Samotné vonkajšie ožiarenie bez kontaminácie.|Bežné tepelné poškodenie odevu.|Kontaminácia znamená prítomnosť rádioaktívnej látky. Ožiarenie môže prebehnúť aj bez usadenia takejto látky na človeku.
Prečo môže byť potrebné odstrániť kontaminovaný vrchný odev podľa pokynov?|Odstráni sa časť látky zachytenej na odeve.|Odev po vyzlečení automaticky stratí rádioaktivitu.|Odloženie odevu nahradí všetky ďalšie pokyny na očistu.|S odevom sa manipuluje opatrne a podľa odporúčaní, aby sa znečistenie nešírilo.
Aký postup je vhodný pri požiari s hustým dymom?|Zostať mimo dymu a prenechať zásah vybaveným hasičom.|Prejsť dymom s mokrou šatkou, ak sa dá vidieť východ.|Prejsť pri stene, lebo tam dym neobsahuje škodliviny.|Dym môže obsahovať toxické látky a málo kyslíka; šatka neposkytuje spoľahlivú ochranu.
Prečo sa pri chemickej havárii nedá odporučiť vždy rovnaké miesto úkrytu?|Postup závisí od látky a aktuálnej situácie.|Každý plyn zostáva pri zemi, preto stačí vyjsť vyššie.|Každý nebezpečný plyn stúpa, preto je vhodná pivnica.|Úkryt či evakuáciu treba prispôsobiť konkrétnemu ohrozeniu.
Kto má likvidovať neznámu nebezpečnú látku na školskom dvore?|Odborne vybavené a poverené osoby.|Ktokoľvek s gumovými rukavicami a vedrom vody.|Skupina žiakov pod dohľadom dospelého bez znalosti látky.|Nevhodné čistenie môže spôsobiť reakciu alebo rozšíriť znečistenie.
Čo znamená symbol rádioaktivity na zariadení?|Riziko ionizujúceho žiarenia.|Prítomnosť biologicky infekčného materiálu.|Nebezpečenstvo silného magnetického poľa.|Rešpektuj označenie a nevstupuj do nepovolených priestorov.
Ako reaguješ na neoverenú správu o havárii?|Overím zdroj, čas, miesto a aktuálne oficiálne pokyny.|Prepošlem ju s dodatkom „neviem, či je to pravda“.|Za potvrdenie považujem rovnaký text na troch neznámych účtoch.|Zdieľanie neoverených informácií môže komplikovať pomoc.
Čo je dôležité pri pobyte väčšej skupiny v úkryte?|Koordinovaný režim, hygiena a voľné priechody.|Uloženie batožiny k východom, aby bola pri odchode po ruke.|Individuálne otváranie vetrania podľa pocitu každého človeka.|Spoločná disciplína chráni aj zraniteľných členov skupiny.
@8|aid
Človek sa topí, ty nie si vycvičený záchranca. Čo urobíš?|Volám pomoc a zo zabezpečeného brehu podám alebo hodím pomôcku.|Vstúpim do vody, pokiaľ ešte dočiahnem nohami na dno.|Doplavím k nemu, keďže pokojné plávanie už zvládam.|Záchrana z bezpečia znižuje riziko, že sa utopí aj pomocník.
Niekto sa dotýka vodiča pod napätím. Čo je prvé?|Nedotýkať sa ho, privolať pomoc a bezpečne zaistiť odpojenie.|Najprv ho odtiahnuť za suchú časť oblečenia bez odpojenia.|Najprv ho odsúvať predmetom, ktorého izolačné vlastnosti nepoznám.|Kým trvá elektrické nebezpečenstvo, priblíženie môže ohroziť aj záchrancu.
Pri ochladzovaní popáleniny bolesť po dvoch minútach ustúpi. Čo ďalej?|Pokračovať chladnou tečúcou vodou aspoň do 20 minút a chrániť zvyšok tela.|Prestať chladiť, keďže ústup bolesti znamená ukončenie poškodenia.|Prejsť na priamy ľad, aby sa zvyšný čas chladenia skrátil.|Ústup bolesti nie je dôvod skrátiť odporúčané chladenie. Chladíme postihnuté miesto a predchádzame podchladeniu zvyšku tela.
Odev je prilepený k popálenine. Čo urobíš?|Prilepenú časť ponechám, aby sa koža ďalej nepoškodila.|Odstránim ju po krátkom namočení aj s kožou.|Oddeľujem ju postupne od okrajov čistou pinzetou.|Strhávanie môže ďalej poškodiť kožu.
Počas KPR AED ohlási analýzu rytmu. Čo musí skupina urobiť?|Na pokyn prístroja prerušiť dotyk s človekom vrátane stláčania.|Prerušiť iba vdychy a ďalej stláčať počas merania.|Dotýkať sa ho môže človek, ktorý má rukavice.|Pohyb a dotyk môžu rušiť analýzu. Nikto sa človeka nedotýka ani pri podaní výboja; potom sa pokračuje podľa AED.
Ako pomôžeš pri kŕčovom záchvate?|Chránim pred úrazom a nič nevkladám do úst.|Podopriem hlavu a pevne zadržím trhajúce sa končatiny.|Medzi zuby vložím mäkkú látku na ochranu jazyka.|Nesnaž sa zastaviť kŕče silou; sleduj čas a podľa stavu privolaj 155.
Dospelý pri jedle kašle účinne a dokáže hovoriť. Čo urobíš?|Povzbudím ku kašľu a sledujem účinnosť dýchania.|Hneď začnem s údermi do chrbta aj pri účinnom kašli.|Podám vodu, aby sa sústo ľahšie posunulo nadol.|Účinný kašeľ môže prekážku uvoľniť; pri zhoršení treba ihneď pomôcť.
Počas horúčavy je človek zmätený a veľmi horúci. Čo je správne?|Volám 155 a hneď začnem s bezpečným ochladzovaním.|Najprv ho nechám zaspať v tieni a až potom posúdim stav.|Prinútim ho vypiť veľa vody aj pri zhoršenom vedomí.|Zmätenosť pri prehriatí je závažná; človeku s poruchou vedomia nič nepodávaj ústami.
Pri hromadnej nehode si žiak bez záchranárskeho výcviku. Čo urobíš?|Posúdim bezpečnosť, volám 112 a plním bezpečné pokyny.|Najprv spočítam ľudí medzi vozidlami a až potom zavolám.|Začnem presúvať všetkých, ktorí nevedia samostatne vystúpiť.|Organizácia pomoci a vlastná bezpečnosť sú rozhodujúce.
Prečo alkohol nie je vhodný na zahriatie podchladeného?|Pocit tepla neznamená menšie tepelné straty.|Alkohol je nevhodný iba vtedy, keď je nápoj studený.|Malé množstvo alkoholu môže nahradiť suchý odev.|Postihnutého chránime pred chladom a podľa závažnosti voláme pomoc.
@8|orientation
Kráčaš na západ a otočíš sa o 90° doľava. Akým smerom pokračuješ?|Na juh.|Na sever.|Na východ.|Pri pohľade na západ je juh po ľavej ruke. Ide o zmenu z azimutu 270° na 180°.
Aký je opačný azimut k smeru 315°?|135°.|225°.|45°.|Opačný smer sa líši o 180°. Pri 315° odpočítame 180° a dostaneme 135°.
Pri postupe podľa azimutu je na ceste nebezpečný zráz. Čo urobíš?|Zastavím a zvolím bezpečnú obchádzku s kontrolou polohy.|Obídem zráz a pokračujem rovnako ďaleko bez overenia polohy.|Ponechám priamy smer, ak na mape nie je zráz vyznačený.|Azimut je smerová pomôcka, nie záruka priechodnej cesty.
[map] Postupuješ od rieky ku škole a ďalej k lesu. Ako zmeníš smer pri škole?|Z 0° na 90°, teda doprava.|Z 0° na 270°, teda doľava.|Zo 180° na 90°, teda doľava.|Od rieky ku škole ideš na sever (0°). K lesu potom ideš na východ (90°), teda odbočíš doprava.
Na mape 1 : 25 000 meria trasa 8 cm. Obchádzka pridá ďalšie 2 cm. Koľko je to spolu?|2,5 km.|2 km.|3 km.|Spolu 10 cm pri 250 metroch na centimeter predstavuje 2 500 m, čiže 2,5 km.
Čo má obsahovať tabuľka pochodu podľa azimutov?|Smery a vzdialenosti jednotlivých úsekov aj kontrolné body.|Iba celkový azimut medzi štartom a cieľom kľukatej trasy.|Iba zoznam vzdialeností bez rozlíšenia odbočiek a smerov.|Kontrolné body pomáhajú odhaliť odchýlku od plánovanej trasy.
Prečo na túru berieme aj záložný spôsob orientácie?|Jedno zariadenie môže zlyhať alebo sa vybiť.|Dve mapové aplikácie v jednom telefóne pokrývajú aj poruchu batérie.|Papierová mapa má význam iba tam, kde existuje mobilný signál.|Papierová mapa a kompas dopĺňajú elektronické pomôcky.
Čo je užitočné pri hlásení polohy záchranárom v teréne?|Súradnice s ich formátom a opis miesta pre operátora.|Odhad vzdialenosti od obce bez smeru a orientačných bodov.|Skrátené súradnice bez informácie, v akom formáte sú zobrazené.|Presnú polohu potvrď operátorovi a doplň viditeľné body.
Skupina má lekárničku, ale dvaja nemajú prilbu. Ako posúdiš pripravenosť na cyklovýlet?|Lekárnička nenahrádza chýbajúce ochranné vybavenie.|Lekárnička postačí, ak trasa vedie iba po rovnom úseku.|Chýbajúce prilby vyváži znalosť ošetrovania drobných rán.|Pripravenosť zahŕňa prevenciu aj pomoc. Pomôcky na ošetrenie nenahrádzajú ochranu pred úrazom.
Ktoré miesto je nebezpečné na použitie turistického variča?|V stane, aj keď je čiastočne pootvorený.|Na vhodnom stabilnom povolenom mieste vonku podľa návodu.|Na určenom vonkajšom stanovišti s odstupom od horľavín.|V stane hrozí požiar aj otrava oxidom uhoľnatým.
@8|nature
Čo znamená fragmentácia krajiny?|Rozdelenie biotopu na oddelené menšie časti.|Postupné pribúdanie druhov v prepojenom prostredí.|Pravidelné striedanie sezón v tom istom prostredí.|Cesty a zástavba môžu obmedziť pohyb a rozmnožovanie organizmov.
Ako môže pomôcť ekodukt ponad cestu?|Umožní živočíchom prekonať dopravnú bariéru.|Nahradí potrebu zachovať biotopy na oboch stranách cesty.|Zabráni každému stretu so zvieraťom na celej cestnej sieti.|Ekodukt zmierňuje bariérový účinok dopravy.
Čo je vhodné pri výsadbe v prírodne cennom území?|Zvoliť vhodný postup a druhy podľa odborného posúdenia.|Vybrať najrýchlejšie rastúci druh bez ohľadu na pôvod.|Vysadiť čo najviac stromov aj na prirodzene bezlesnej lokalite.|Nevhodná výsadba môže zmeniť alebo poškodiť miestny ekosystém.
Po povolenom táborení ostali zvyšky jedla, špagát a jamka po kolíku. Čo odnášame?|Všetok odpad vrátane zvyškov jedla a špagátu.|Špagát, zvyšky jedla necháme voľne žijúcim zvieratám.|Špagát, zvyšky jedla zahrnieme do jamky po kolíku.|Aj biologické zvyšky si odnášame. Miesto upravíme šetrne podľa miestnych pravidiel, bez ďalšieho rozrývania pôdy.
Aký problém spôsobuje svetelné znečistenie?|Môže meniť orientáciu a životné rytmy organizmov.|Má vplyv na prírodu iba vtedy, keď je svetlo farebné.|Ovplyvňuje ľudí, ale nočné živočíchy sa mu úplne prispôsobia.|Zbytočné nočné osvetlenie ovplyvňuje aj prírodné prostredie.
Ktorý krok obmedzí plytvanie jedlom na viacdňovej túre?|Plán porcií podľa ľudí a podmienok skladovania.|Veľká rezerva rýchlo sa kaziaceho jedla bez chladenia.|Vylúčenie plánovania, zvyšky sa vždy rozdelia zvieratám.|Primerané plánovanie šetrí potraviny aj miesto v batohu.
Čo spravíš pri úhyne väčšieho počtu rýb v potoku?|Vyhnem sa kontaktu a nahlásim miesto a pozorovania.|Odoberiem vzorku holými rukami a až potom ohlásim nález.|Počkám, či sa voda vyčistí, ak práve nevidím zdroj úniku.|Hromadný úhyn môže signalizovať znečistenie alebo iný vážny problém.
Prečo nemožno posudzovať vplyv výrobku iba podľa obalu?|Vplyv vzniká aj pri výrobe, doprave a používaní.|Recyklovateľný obal ruší vplyvy výroby samotného výrobku.|Hmotnosť obalu sama určuje celkovú ekologickú záťaž výrobku.|Užitočné je uvažovať o celom životnom cykle výrobku.
Čo je bezpečná dobrovoľnícka pomoc po povodni?|Organizovaná činnosť na posúdenom mieste s dohľadom a výbavou.|Samostatné upratovanie pivnice, keď už klesla hladina vody.|Zber odpadu v zaplavenom objekte len podľa jeho vzhľadu.|Po katastrofe môžu pretrvávať skryté riziká.
Ktoré opatrenie podporuje druhovú pestrosť školského dvora?|Rozmanitá vhodná vegetácia a pestré stanovištia.|Jednotný často kosený trávnik na celej ploche.|Nahradenie všetkých miestnych druhov jedným okrasným druhom.|Rôznorodé prostredie poskytuje viac úkrytov a zdrojov potravy.
@9|civil
Aké je hlavné poslanie civilnej ochrany?|Príprava a opatrenia na ochranu ľudí a majetku pri ohrození.|Predovšetkým zdravotná liečba pacientov po skončení udalosti.|Predovšetkým vyšetrovanie príčin trestných činov pri udalosti.|Civilná ochrana zahŕňa prípravu, varovanie aj opatrenia pri mimoriadnych udalostiach.
Aký je medzinárodný rozlišovací znak civilnej ochrany?|Modrý rovnostranný trojuholník na oranžovom podklade.|Oranžový rovnostranný trojuholník na modrom podklade.|Modrý rovnostranný trojuholník na bielom podklade.|Tento znak identifikuje civilnú ochranu podľa medzinárodného humanitárneho práva.
Obec preberá krízový plán susednej obce. Má však aj chemický sklad pri rieke. Čo potrebuje doplniť?|Posúdenie vlastných rizík a na ne nadväzujúce opatrenia.|Iba zmenu názvov ulíc, rovnaký počet obyvateľov zaručí vhodnosť plánu.|Iba viac evakuačných vozidiel bez zmeny trás a pokynov.|Podobná veľkosť obcí neznamená rovnaké riziká. Plán má vychádzať z miestnych podmienok a ich možných súvislostí.
Kedy užiť jódové tablety pri jadrovej havárii?|Na oficiálny pokyn a podľa určeného dávkovania.|Pri každej neoverenej správe o udalosti v jadrovom zariadení.|Preventívne pri akomkoľvek poplachu v okolí elektrárne.|Načasovanie a dávka sú dôležité; tablety nie sú univerzálnou ochranou pred žiarením.
Rodina užila jódové tablety podľa pokynu. Stále platí nariadenie zostať v úkryte. Čo nasleduje?|Dodržiavať aj ukrytie a ďalšie vydané pokyny.|Ukončiť ukrytie, pretože tablety už účinkujú.|Vyjsť von, ak od užitia uplynul čas na vstrebanie.|Profylaxia má obmedzený účel. Jej správne užitie neruší ďalšie ochranné opatrenia.
Nájdeš poškodenú budovu s možnými zavalenými osobami. Čo urobíš?|Nevstupujem, volám 112 a odovzdám pozorovania.|Odstránim najprv ľahké trosky pod poškodeným stropom.|Vstúpim, ak pri vchode ešte nevidím pohyb muriva.|Neodborný vstup alebo zásah môže spôsobiť ďalší zával.
Najkratšia evakuačná cesta vedie nízko pri rieke a hrozí povodeň. Čo má rozhodovať pri výbere?|Priechodnosť a bezpečnosť vzhľadom na riziko aj potreby ľudí.|Najkratšia vzdialenosť, lebo kratší pobyt vonku vždy zníži riziko.|Najväčší počet jazdných pruhov bez ohľadu na zaplavenie.|Dobrá trasa musí byť použiteľná pri konkrétnom ohrození. Vzdialenosť ani šírka samy nezaručujú bezpečnosť.
Dvojminútový stály tón zaznie bez zrozumiteľného hlásenia. Vieš z tónu samotného potvrdiť návrat do budovy?|Nie, treba overiť hlásenie; taký tón sa používa aj pri oznámenej skúške.|Áno, stály tón vždy znamená, že aktuálne nebezpečenstvo už skončilo.|Áno, pokiaľ od predchádzajúceho varovania uplynuli dve minúty.|Koniec ohrozenia sa vyhlasuje dvojminútovým stálym tónom, ale rovnaký tón môže patriť oznámenej skúške. Kontext a pokyny treba overiť.
Ako najlepšie podporíš zraniteľného suseda počas organizovanej evakuácie?|Dohodnem potreby so susedom a zodpovednými osobami.|Odveziem ho vlastnou trasou bez informovania organizátorov.|Oznámim jeho potreby až po evakuácii ostatných z domu.|Koordinácia pomoci je dôležitejšia než nebezpečné improvizovanie.
Na sociálnej sieti vidíš záber zo záplav bez miesta a času. Čo spravíš?|Overím pôvod, čas, miesto a príslušné oficiálne informácie.|Za dôkaz aktuálnosti vezmem dátum jeho posledného zdieľania.|Za potvrdenie lokality vezmem komentár najaktívnejšieho účtu.|Pravý záber môže byť zavádzajúci, ak pochádza z iného miesta alebo času.
@9|aid
Pri náleze zraneného mimo obce je poradie úvah aké?|Bezpečnosť miesta, privolanie pomoci a posúdenie stavu.|Identifikácia zraneného, zistenie poistenia a potom stav.|Presun bližšie k ceste, privolanie pomoci a potom bezpečnosť.|Život zachraňujúce úkony a spojenie s operátorom majú prednosť pred nepodstatnými úlohami.
Kamarát prinesie AED k nereagujúcemu dospelému, ktorý nedýcha normálne. Čo spravíte?|Zapneme AED a postupujeme podľa neho s minimom prestávok KPR.|Dokončíme ešte päť minút KPR, až potom zapneme AED.|Zapneme AED, ale elektródy nalepíme až pri príchode zdravotníka.|AED je určený aj laikom a hlasovými pokynmi vedie postup.
Pri KPR dospelého nevieš alebo nedokážeš robiť vdychy. Čo je vhodné?|Stláčam hrudník a riadim sa pokynmi operátora.|Po každej tridsiatke čakám, či nepríde niekto na vdychy.|Stláčam pomalšie, aby sa chýbajúce vdychy vykompenzovali.|Samotné stláčanie hrudníka je pri dospelom lepšie než neposkytnutie pomoci.
Pri nácviku KPR dospelého máš správne tempo, ale medzi stlačeniami zostávaš opretý o hrudník. Čo opravíš?|Po každom stlačení uvoľním tlak a dovolím návrat hrudníka.|Zvýšim tempo, aby sa kratšie uvoľnenie vyrovnalo.|Znížim hĺbku, ale ponechám trvalý tlak na hrudník.|Úplné uvoľnenie hrudníka umožňuje jeho návrat a plnenie srdca. Správne tempo nenahrádza správne uvoľnenie.
Nereagujúci človek na boku prestane normálne dýchať. Čo urobíš?|Položím ho na chrbát a začnem KPR podľa 155.|Ponechám ho na boku a budem dlhšie sledovať dychy.|Najprv ho posadím a pokúsim sa ho rozhýbať.|Dýchanie treba kontrolovať priebežne; zmena vyžaduje okamžitú reakciu.
Aký je význam darovania krvi?|Krv a jej zložky pomáhajú liečiť a zachraňovať pacientov.|Darovaná krv sa používa bez posudzovania vhodnosti pre príjemcu.|Darcovstvo nahrádza potrebu iných spôsobov zastavenia krvácania.|Darcovstvo má vekové a zdravotné podmienky, ktoré posudzuje odberové pracovisko.
Čo pomáha znížiť riziko ochorení prenášaných kliešťami?|Oblečenie, vhodný repelent a kontrola tela po návrate.|Iba kontrola bolestivých miest, prisatie vždy cítime.|Iba repelent, po jeho použití už netreba telo kontrolovať.|Prevencia kombinuje ochranu pri pobyte vonku a včasnú kontrolu tela.
Žiak je očkovaný proti kliešťovej encefalitíde. Ktoré tvrdenie je správne?|Stále potrebuje ochranu pred kliešťami, očkovanie nechráni pred boreliózou.|Kontrola tela už nemá význam, očkovanie pokrýva choroby od kliešťov.|Ochranu potrebuje iba dovtedy, kým sa neobjaví prvé prisatie.|Kliešťová encefalitída a lymská borelióza sú odlišné ochorenia. Očkovanie proti jednej nenahrádza prevenciu prisatia.
Ako zorganizuješ pomoc pri náhlom kolapse, keď je viac svedkov?|Určím konkrétne osoby na volanie a AED a začnem potrebnú pomoc.|Požiadam všeobecne o pomoc a predpokladám, že úlohy sú rozdelené.|Nechám všetkých hľadať AED a zostanem čakať na ich návrat.|Jasné rozdelenie úloh znižuje riziko, že nikto nezareaguje.
Prečo zranenému s poruchou vedomia nepodávame jedlo ani nápoj?|Nedokáže bezpečne prehĺtať a môže obsah vdýchnuť.|Každý nápoj okamžite zhorší prekrvenie poranenej časti tela.|Jedlo by zabránilo záchranárom posúdiť stav vedomia.|Pri poruche vedomia nemusí bezpečne prehĺtať.
@9|orientation
Na 12 km pri tempe 4 km/h má skupina tri prestávky po 15 minút a rezervu 30 minút. Kedy má plánovať návrat pri štarte o 8:30?|O 12:45.|O 12:15.|O 13:15.|Chôdza 3 h + prestávky 45 min + rezerva 30 min = 4 h 15 min. Po pripočítaní k 8:30 dostaneme 12:45.
Prečo pri náročnej trase nestačí poznať iba kilometre?|Dôležité sú prevýšenie, terén, počasie a skupina.|Náročnosť určuje výlučne priemerná dĺžka jedného kroku.|Rovnaká značená vzdialenosť vyžaduje vždy rovnaký čas.|Rovnaká vzdialenosť môže mať veľmi odlišnú náročnosť.
Ako zvolíš tempo skupiny na túre?|Podľa schopností celej skupiny vrátane pomalších členov.|Podľa priemerného tempa, aj keď niektorí opakovane zaostávajú.|Podľa najsilnejších, pomalší dostanú dlhší čas na dobehnutie.|Súdržná skupina vie skôr rozpoznať únavu a poskytnúť pomoc.
[map] Ideš od stanu ku škole a potom k lesu. O koľko a kam sa otočíš pri škole?|O 90° doľava.|O 90° doprava.|O 180° doľava.|Ku škole prichádzaš smerom na juh (180°). K lesu pokračuješ na východ (90°), teda sa otočíš o štvrť otáčky doľava.
Mapa má mierku 1 : 50 000. Pôvodný úsek dlhý 2 cm nahradí obchádzka dlhá 5 cm. O koľko sa trasa predĺži?|O 1,5 km.|O 2,5 km.|O 3,5 km.|Rozdiel je 5 − 2 = 3 cm. Jeden centimeter predstavuje 500 m, preto je predĺženie 1 500 m.
Ideš azimutom 250° a potrebuješ presný opačný smer. Ktorý azimut zvolíš?|70°.|110°.|160°.|Od 250° odpočítame 180° a dostaneme 70°. Výsledok musí zostať v rozsahu plného kruhu.
Skupina mešká a k cieľu vedie dlhý odkrytý hrebeň. Blíži sa búrka. Čo je rozumné?|Včas zvoliť bezpečný ústup podľa situácie a mapy.|Pokračovať rýchlejšie, pretože cieľ je už bližší než štart.|Rozdeliť skupinu na rýchlu a pomalú bez vedúceho pri oboch.|Dosiahnutie cieľa nesmie mať prednosť pred bezpečným návratom.
Čo znamená údaj ±30 m pri polohe GPS?|Odhad neistoty, ktorý treba porovnať s mapou a terénom.|Záruku, že skutočná poloha nikdy neleží ďalej než 30 m.|Údaj, že sa vždy nachádzame na chodníku do 30 m od bodu.|Polohu porovnávaj s mapou a terénom, najmä pri okrajoch či rázcestiach.
Čo je užitočný plán B pri túre?|Kratšia alebo ústupová trasa overená ešte pri plánovaní.|Najbližšia viditeľná skratka vybraná až pri únave skupiny.|Druhá aplikácia zobrazujúca tú istú trasu bez možnosti ústupu.|Alternatíva pomáha pri únave, zhoršení počasia alebo uzávere.
Ako pripravíš telefón na dlhšiu túru?|Nabitie, offline podklady a nezávislá záloha orientácie.|Dve mapové aplikácie v jednom nenabitom telefóne.|Plné nabitie bez mapy, s predpokladom signálu na celej trase.|Technika pomáha, no mala by mať zálohu.
@9|nature
Obec môže ročne odoberať zo zdroja najviac toľko vody, koľko sa dlhodobo obnoví bez poškodenia prostredia. Čo vystihuje udržateľný prístup?|Prispôsobiť odber obnove aj potrebám ekosystému.|Zvýšiť odber vždy, keď nový vrt krátkodobo poskytne viac vody.|Určovať odber iba podľa minuloročnej spotreby obyvateľov.|Udržateľnosť zohľadňuje dlhodobú obnovu a fungovanie prostredia, nielen aktuálnu dostupnosť zdroja.
Prečo sa návštevnosť citlivých miest niekedy obmedzuje?|Mnoho malých zásahov môže spolu prekročiť únosnú záťaž.|Prírode škodia iba jednotlivé veľké zásahy, počet ľudí nehrá rolu.|Obmedzenie má význam iba vtedy, keď sa zakáže každá návšteva.|Aj malé zásahy veľkého množstva ľudí môžu mať výrazný súhrnný účinok.
Škola chce vysadiť stromy. Aký plán je najlepší?|Vhodné druhy a miesto, plán starostlivosti aj kontrola ujatia.|Čo najviac sadeníc, úspech posúdiť podľa počtu pri výsadbe.|Najrýchlejší rast bez zohľadnenia vody a miestnych podmienok.|Výsledok závisí aj od prežitia a starostlivosti po výsadbe.
Čo má prednosť pri organizovaní čistenia čiernej skládky žiakmi?|Posúdenie rizík, vhodný rozsah práce a dohľad.|Úplné odstránenie odpadu, bezpečnosť posúdiť podľa jeho zápachu.|Najrýchlejší postup, ochranné pomôcky rozdeliť až po začiatku práce.|Nebezpečný odpad a rizikové miesta nepatria do neodborného žiackeho zásahu.
Obec chce zmierniť horúčavu na námestí. Ktorý návrh priamo pomáha prispôsobeniu na horúčavy?|Tieň, vhodná zeleň a zadržiavanie dažďovej vody.|Viac triediacich nádob bez zmeny povrchu a tieňa.|Výmena tabúľ za recyklovaný materiál bez úpravy priestoru.|Triedenie aj recyklované materiály môžu byť užitočné, ale samy neriešia prehrievanie námestia. Tieň, vegetácia a voda naň vplývajú priamo.
Škola vysadila 100 stromov. O rok ich žije 35. Čo je najvýstižnejšie hodnotenie?|Počet vysadených stromov nestačí, treba sledovať prežitie a príčiny strát.|Projekt splnil cieľ už počtom sadeníc bez ohľadu na ich ďalší stav.|Straty nemajú význam, ak bola výsadba dobre zdokumentovaná fotografiami.|Výstup činnosti a jej dlhodobý výsledok nie sú to isté. Kontrola umožňuje zlepšiť výber miesta, druhov a starostlivosť.
Výrobok tvrdí „100 % zelený“, ale bez údajov. Čo je rozumné?|Žiadať konkrétne overiteľné údaje o tvrdenom prínose.|Považovať výraz „100 %“ za potvrdenie nezávislého overenia.|Porovnať iba farbu obalov s podobnými výrobkami.|Všeobecný slogan bez dôkazov môže byť zavádzajúci.
Čo môže obmedziť fragmentáciu prírody pri výstavbe?|Prepojené biotopy a vhodne umiestnené priechody.|Zachovanie rovnakej plochy zelene v úplne izolovaných ostrovoch.|Výsadba stromov popri bariére bez priechodu medzi jej stranami.|Priechodnosť krajiny je dôležitá pre migráciu aj genetickú rozmanitosť.
Turista odniesol odpad, ale pri fotení opustil povolenú trasu v citlivom území. Ako hodnotíš jeho postup?|Jeden správny krok nevyvažuje poškodenie porastu a porušenie pravidla.|Odnesený odpad mu umožňuje krátko vstúpiť aj mimo povolenej trasy.|Postup je prijateľný, pokiaľ miesto opustil skôr než ostatní turisti.|Ohľaduplnosť sa týka celej návštevy. Ochrana pôdy a živočíchov nie je nahradená uprataním odpadu.
Dva návrhy ochrany lesa sa opierajú o odlišné údaje. Čo pomôže pri rozhodovaní najviac?|Porovnať zdroje, metódy, obdobie a miestne podmienky údajov.|Vybrať návrh s väčším počtom podporujúcich komentárov.|Vybrať návrh s presnejšími číslami bez kontroly ich pôvodu.|Samotná presnosť čísla ani popularita nezaručujú spoľahlivosť. Podstatné sú overiteľné podklady a ich použiteľnosť v danej lokalite.
`;
let grade, topic, serial = 0;
const questions = [];
for (const line of data.trim().split('\n')) {
  if (line.startsWith('@')) {
    const parts = line.slice(1).split('|');
    grade = Number(parts[0]); topic = parts[1]; serial = 0;
    continue;
  }
  const parts = line.split('|');
  if (parts.length !== 5) throw new Error(`Neplatný formát otázky: ${line}`);
  const [raw, correct, wrong1, wrong2, explanation] = parts;
  questions.push({ id: `${grade}-${topic}-${++serial}`, grade, topic,
    question: raw.replace('[map] ', ''), answers: [correct, wrong1, wrong2],
    explanation, visual: raw.startsWith('[map]') ? 'map' : null });
}
if (typeof module !== 'undefined' && module.exports) module.exports = questions;
else root.QUESTION_BANK = questions;
})(typeof globalThis !== 'undefined' ? globalThis : this);
